<!DOCTYPE html>
<html lang="el">
<head>
<!-- UI consolidation v3.20: shared design system in assets/common.css?v=3.20.9"UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="Υπολογισμός μορίων για την προκήρυξη ΑΣΕΠ 2ΕΑ/2025 για μέλη Ειδικού Εκπαιδευτικού Προσωπικού (ΕΕΠ).">
<title>Υπολογισμός μορίων 2ΕΑ/2025</title>
<link rel="stylesheet" href="assets/common.css?v=3.20.9">
</head>
<body class="edu-ui edu-calc-standard edu-page-ea2">
<?php require_once __DIR__ . '/includes/header.php'; ?>
<div class="app">
<section class="hero"><h1>Υπολογισμός μορίων 2ΕΑ/2025</h1><p>Ενδεικτικός υπολογισμός για τον αξιολογικό πίνακα Γ1΄ μελών <strong>Ειδικού Εκπαιδευτικού Προσωπικού (Ε.Ε.Π.)</strong>.</p><div class="meta"><span>2ΕΑ/2025</span><span>ΠΕ21–ΠΕ31</span><span>Ακαδημαϊκά έως 120</span><span>Προϋπηρεσία έως 120</span><span>Έλεγχος πρόταξης</span><span>Άδειες &amp; βεβαιώσεις</span></div></section>
<div class="layout"><main>
<section class="card"><h2>1. Κλάδος και πρόταξη</h2><p class="cap">Ο κλάδος δεν αλλάζει τον βασικό πίνακα μοριοδότησης, αλλά ενεργοποιεί ειδικές επισημάνσεις και κανόνες πρόταξης.</p>
<div class="field"><label for="branch">Κλάδος ΕΕΠ</label><select id="branch"><option value="">— Επιλογή —</option><option value="PE21">ΠΕ21 — Θεραπευτών Λόγου</option><option value="PE22">ΠΕ22 — Επαγγελματικών Συμβούλων</option><option value="PE23">ΠΕ23 — Ψυχολόγων</option><option value="PE25">ΠΕ25 — Σχολικών Νοσηλευτών</option><option value="PE28">ΠΕ28 — Φυσιοθεραπευτών</option><option value="PE29">ΠΕ29 — Εργασιοθεραπευτών–Εργοθεραπευτών</option><option value="PE30">ΠΕ30 — Κοινωνικών Λειτουργών</option><option value="PE31">ΠΕ31 — Εξειδικευμένου</option></select></div>
<div id="branchNote" class="info">Επίλεξε κλάδο για να εμφανιστούν οι ειδικές επισημάνσεις.</div>
<div class="checkrow"><input type="checkbox" id="pedagogical"><label for="pedagogical">Πιστοποιημένη Παιδαγωγική και Διδακτική Επάρκεια<small>Δεν προσθέτει μόρια, αλλά αποτελεί κριτήριο πρόταξης.</small></label></div>
<div id="pe23Wrap" class="field hidden"><label for="schoolPsych">ΠΕ23 — Εξειδίκευση στη Σχολική Ψυχολογία<small>Προσόν πρόταξης, όχι ξεχωριστή μοριοδότηση από μόνο του.</small></label><select id="schoolPsych"><option value="none">Δεν διαθέτω εξειδίκευση</option><option value="degree">Διδακτορικό ή μεταπτυχιακό στη Σχολική Ψυχολογία</option><option value="experience">Τουλάχιστον 50 μήνες προϋπηρεσίας ως ψυχολόγος στην Π/θμια ή Δ/θμια</option></select><div id="schoolPsychReminder" class="note hidden">Η επιλογή εξειδίκευσης μέσω τίτλου δεν προσθέτει αυτόματα μόρια. Δήλωσε τον αντίστοιχο διδακτορικό/μεταπτυχιακό τίτλο και στην ενότητα Ακαδημαϊκών.</div></div>
<div class="field-grid"><div class="checkrow"><input type="checkbox" id="braille"><label for="braille">Πιστοποιημένη επάρκεια Braille<small>Ειδική προτεραιότητα για μαθητές με προβλήματα όρασης.</small></label></div><div class="checkrow"><input type="checkbox" id="signLanguage"><label for="signLanguage">Πιστοποιημένη επάρκεια ΕΝΓ<small>Ειδική προτεραιότητα για κωφούς/βαρήκοους μαθητές.</small></label></div></div>
</section>
<section class="card" id="licenseCard"><h2>2. Υποχρεωτικές άδειες &amp; βεβαιώσεις συμμετοχής</h2><p class="cap">Δεν μοριοδοτούνται, αλλά όπου προβλέπονται αποτελούν πρόσθετα τυπικά προσόντα ένταξης του κλάδου.</p>
<div id="licenseIntro" class="info">Επίλεξε κλάδο για να εμφανιστούν τα απαιτούμενα πρόσθετα επαγγελματικά δικαιολογητικά.</div>
<div id="pe25RouteWrap" class="field hidden"><label for="pe25Route">ΠΕ25 — Διαδρομή βασικού επαγγελματικού τίτλου<small>Η απαιτούμενη άδεια και η επαγγελματική εγγραφή διαφέρουν ανάλογα με τον τίτλο.</small></label><select id="pe25Route"><option value="">— Επιλογή διαδρομής —</option><option value="nursing">Τίτλος Νοσηλευτικής</option><option value="health_visitor">Τίτλος Επισκέπτη/Επισκέπτριας Υγείας</option></select></div>
<div id="licenseRequirements"></div>
<div id="licenseStatus" class="priority">Δεν έχει επιλεγεί κλάδος.</div>
<div class="note"><strong>Σημαντικό:</strong> ο έλεγχος αυτός αφορά μόνο τις ειδικές άδειες, βεβαιώσεις και εγγραφές σε επαγγελματικούς φορείς. Δεν επιβεβαιώνει τον βασικό τίτλο σπουδών ή όλα τα λοιπά τυπικά προσόντα της προκήρυξης. Τα απαιτούμενα προσόντα πρέπει να υφίστανται έως τη λήξη της προθεσμίας των αιτήσεων.</div>
</section>
<section class="card"><h2>3. Ακαδημαϊκά προσόντα</h2><p class="cap">Μέγιστο κατηγορίας Α: 120 μόρια.</p>
<div class="field"><label for="degreeGrade">Βαθμός βασικού πτυχίου (5–10)<small>Βαθμός × 2,5 · ανώτατο 25. Αν η κλίμακα είναι διαφορετική, γίνεται αναγωγή στην 10βάθμια.</small></label><input id="degreeGrade" type="number" min="5" max="10" step="0.01" inputmode="decimal" placeholder="π.χ. 7,84"></div><div id="gradeWarning" class="warning hidden">Ο βαθμός πρέπει να είναι από 5,00 έως 10,00.</div>
<div class="checkrow"><input type="checkbox" id="secondDegree"><label for="secondDegree">Δεύτερο πτυχίο ΑΕΙ<small>+7 μόρια, εφόσον δεν αποτελεί τυπικό προσόν διορισμού.</small></label></div>
<div class="checkrow"><input type="checkbox" id="phd"><label for="phd">Μοριοδοτούμενο διδακτορικό δίπλωμα<small>+40 μόρια.</small></label></div>
<div class="field"><label for="masters">Μοριοδοτούμενοι μεταπτυχιακοί τίτλοι / integrated master<small>1 τίτλος: 20 · 2 ή περισσότεροι: 28 συνολικά. Μην συμπεριλάβεις τίτλο που αποτελεί τυπικό προσόν διορισμού.</small></label><select id="masters"><option value="0">Κανένας — 0</option><option value="1">Ένας — 20</option><option value="2">Δύο ή περισσότεροι — 28</option></select></div>
<div id="formalMasterNote" class="note hidden"><strong>Προσοχή:</strong> για ΠΕ21, ΠΕ22 και ΠΕ31, όταν μεταπτυχιακός τίτλος αποτελεί τυπικό προσόν διορισμού στη συγκεκριμένη διαδρομή ένταξης, ο τίτλος αυτός δεν μοριοδοτείται. Δήλωσε παραπάνω μόνο τους τίτλους που πράγματι μοριοδοτούνται.</div>
<h3>Ξένες γλώσσες — έως δύο</h3><div class="info">Επίλεξε <strong>ποια γλώσσα</strong> και το επίπεδό της. Αν δηλωθεί η ίδια γλώσσα δύο φορές, μοριοδοτείται αυτόματα μόνο το ανώτερο επίπεδο.</div><div class="field-grid"><div class="field"><label for="langName1">1η ξένη γλώσσα</label><select id="langName1"><option value="">— Επιλογή γλώσσας —</option><option value="en">Αγγλική</option><option value="fr">Γαλλική</option><option value="de">Γερμανική</option><option value="it">Ιταλική</option><option value="es">Ισπανική</option><option value="other">Άλλη ξένη γλώσσα</option></select></div><div class="field"><label for="lang1">Επίπεδο 1ης γλώσσας</label><select id="lang1"><option value="0">Καμία / χωρίς μόρια</option><option value="3">Καλή — 3</option><option value="5">Πολύ καλή — 5</option><option value="7">Άριστη — 7</option></select></div><div class="field hidden" id="langOther1Wrap"><label for="langOther1">Ονομασία άλλης 1ης γλώσσας</label><input id="langOther1" type="text" placeholder="π.χ. Πορτογαλική"></div><div class="field"><label for="langName2">2η ξένη γλώσσα</label><select id="langName2"><option value="">— Επιλογή γλώσσας —</option><option value="en">Αγγλική</option><option value="fr">Γαλλική</option><option value="de">Γερμανική</option><option value="it">Ιταλική</option><option value="es">Ισπανική</option><option value="other">Άλλη ξένη γλώσσα</option></select></div><div class="field"><label for="lang2">Επίπεδο 2ης γλώσσας</label><select id="lang2"><option value="0">Καμία / χωρίς μόρια</option><option value="3">Καλή — 3</option><option value="5">Πολύ καλή — 5</option><option value="7">Άριστη — 7</option></select></div><div class="field hidden" id="langOther2Wrap"><label for="langOther2">Ονομασία άλλης 2ης γλώσσας</label><input id="langOther2" type="text" placeholder="π.χ. Πορτογαλική"></div></div><div id="languageWarning" class="note hidden"></div>
<div class="checkrow"><input type="checkbox" id="computer"><label for="computer">Πιστοποιημένη γνώση χειρισμού Η/Υ Α΄ επιπέδου<small>+4 μόρια.</small></label></div><div class="checkrow"><input type="checkbox" id="training"><label for="training">Επιμόρφωση ≥300 ωρών και ≥7 μηνών<small>+2 μόρια · μοριοδοτείται μία επιμόρφωση.</small></label></div>
<div class="training-proof hidden" id="trainingProof">
<div class="training-proof-title">Έλεγχος πιστοποιητικού σεμιναρίου</div>
<div class="training-proof-question">Στο πιστοποιητικό αναγράφονται η ημερομηνία έναρξης και η ημερομηνία λήξης του σεμιναρίου;</div>
<div class="segmented-choice" role="radiogroup" aria-label="Ημερομηνίες έναρξης και λήξης στο πιστοποιητικό">
<label><input type="radio" name="trainingDates" id="trainingDatesYes" value="yes"><span>✓ Ναι</span></label>
<label><input type="radio" name="trainingDates" id="trainingDatesNo" value="no"><span>Όχι</span></label>
</div>
<div class="training-proof-status neutral" id="trainingDatesStatus">Έλεγξε το πιστοποιητικό πριν την υποβολή των δικαιολογητικών.</div>
<small class="training-proof-legal">Σε περίπτωση που στο πιστοποιητικό δεν αναγράφεται η ημεροχρονολογία έναρξης και λήξης του σεμιναρίου, απαιτείται η προσκόμιση σχετικής βεβαίωσης από τον οικείο φορέα. <strong>Σε κάθε περίπτωση πρέπει να προκύπτει ολόκληρο το χρονικό διάστημα των 7 μηνών (6 μήνες και 29 ημέρες δεν γίνεται δεκτό).</strong></small>
</div>
<div class="subtot"><span>Ακαδημαϊκά</span><span class="pill" id="academicSubtotal">0,00</span></div></section>
<section class="card"><h2>4. Εκπαιδευτική προϋπηρεσία</h2><p class="cap">Μέγιστο 120 μόρια. Μην δηλώνεις τον ίδιο μήνα σε περισσότερα από ένα πεδία.</p>
<div class="field-grid"><div class="field"><label for="publicMonths">Κανονική δημόσια προϋπηρεσία<small>1 μόριο/μήνα.</small></label><input id="publicMonths" class="service-months" type="number" min="0" step="1" value="0"></div><div class="field"><label for="hardMonths">Δυσπρόσιτα / καταστήματα κράτησης από 2020–21<small>2 μόρια/μήνα · έως 60 μήνες.</small></label><input id="hardMonths" class="service-months" type="number" min="0" max="60" step="1" value="0"></div></div>
<h3>Τρίμηνες συμβάσεις 2020–2021 και 2021–2022</h3><div class="field-grid"><div class="field"><label for="covid2020">Κανονικές 2020–2021<small>1,5/μήνα · έως 10 μόρια έτους.</small></label><input id="covid2020" class="service-months" type="number" min="0" step="1" value="0"></div><div class="field"><label for="covid2021">Κανονικές 2021–2022<small>1,5/μήνα · έως 10 μόρια έτους.</small></label><input id="covid2021" class="service-months" type="number" min="0" step="1" value="0"></div><div class="field"><label for="covidHard2020">Δυσπρόσιτες 2020–2021<small>3/μήνα · έως 20 μόρια έτους.</small></label><input id="covidHard2020" class="service-months" type="number" min="0" step="1" value="0"></div><div class="field"><label for="covidHard2021">Δυσπρόσιτες 2021–2022<small>3/μήνα · έως 20 μόρια έτους.</small></label><input id="covidHard2021" class="service-months" type="number" min="0" step="1" value="0"></div></div>
<div id="serviceBranchNote" class="info">Η ειδική μοριοδότηση ιδιωτικής σχολικής προϋπηρεσίας με συντελεστή 0,9 δεν αφορά τα μέλη ΕΕΠ-ΕΒΠ.</div><div id="serviceWarning" class="note hidden"></div><div class="subtot"><span>Προϋπηρεσία</span><span class="pill" id="serviceSubtotal">0,00</span></div></section>
<section class="card"><h2>5. Κοινωνικά κριτήρια</h2><div class="field"><label for="children">Αριθμός μοριοδοτούμενων τέκνων<small>3 μόρια ανά τέκνο.</small></label><input id="children" type="number" min="0" step="1" value="0"></div><h3>Αναπηρία — λαμβάνεται μόνο το μεγαλύτερο επιλέξιμο ποσοστό</h3><div class="field-grid"><div class="field"><label for="candidateDisability">Υποψήφιος/α (%)</label><input id="candidateDisability" type="number" min="0" max="100" step="0.01" value="0"></div><div class="field"><label for="spouseDisability">Σύζυγος (%)</label><input id="spouseDisability" type="number" min="0" max="100" step="0.01" value="0"></div><div class="field"><label for="childDisability">Τέκνο (%)</label><input id="childDisability" type="number" min="0" max="100" step="0.01" value="0"></div></div><div class="checkrow"><input type="checkbox" id="marriage4"><label for="marriage4">Έγγαμος βίος τουλάχιστον 4 έτη<small>Απαιτείται για μοριοδότηση αναπηρίας συζύγου.</small></label></div><div class="checkrow"><input type="checkbox" id="mental"><label for="mental">Η αναπηρία του/της υποψηφίου οφείλεται, έστω κατά ποσοστό, σε ψυχική πάθηση<small>Σε αυτή την περίπτωση δεν μοριοδοτείται η αναπηρία του/της υποψηφίου.</small></label></div><div id="socialWarning" class="note hidden"></div><div class="subtot"><span>Κοινωνικά</span><span class="pill" id="socialSubtotal">0,00</span></div></section>
</main><aside class="results"><section class="card"><h2>Αποτέλεσμα</h2><div class="total"><div class="num" id="totalPoints">0,00</div><div class="label">συνολικά μόρια</div></div><div class="result-row"><span>Βαθμός πτυχίου</span><strong id="degreePoints">0,00</strong></div><div class="result-row"><span>Ακαδημαϊκά</span><strong id="academicPoints">0,00</strong></div><div class="result-row"><span>Προϋπηρεσία</span><strong id="servicePoints">0,00</strong></div><div class="result-row"><span>Κοινωνικά</span><strong id="socialPoints">0,00</strong></div><div class="result-row"><span>Άδειες / βεβαιώσεις</span><strong id="licenseResult">—</strong></div><div id="priorityBox" class="priority">Επίλεξε κλάδο για έλεγχο πρόταξης</div><div id="specialPriorityBox" class="priority hidden"></div><div class="actions"><button type="button" id="copyBtn">Αντιγραφή</button><button type="button" class="secondary" id="resetBtn">Μηδενισμός</button></div></section></aside></div>
<div class="source"><strong>Πηγές / Νομική βάση:</strong><br><strong>Βάση υπολογισμού:</strong> Προκήρυξη ΑΣΕΠ 2ΕΑ/2025, Κεφάλαιο Β΄ — τυπικά προσόντα ένταξης, Κεφάλαιο Δ΄ παρ. 10 — Άδειες και Βεβαιώσεις, και Κεφάλαιο Γ΄ — κριτήρια αξιολογικού πίνακα Γ1΄ ΕΕΠ. Οι ενδείξεις «πρόταξης» είναι βοηθητικές και δεν αποτελούν επιπλέον μόρια.</div><div class="credits">Εργαλείο υπολογισμού μορίων · 2ΕΑ/2025</div></div>
<script src="includes/service-calculations.js"></script><script src="includes/social-calculations.js"></script><script src="includes/language-calculations.js"></script><script src="includes/eep-eligibility-calculations.js"></script>
<script>
(function(){"use strict";const $=id=>document.getElementById(id);const n=id=>Number($(id).value)||0;const fmt=v=>(Math.round((Number(v)||0)*100)/100).toLocaleString('el-GR',{minimumFractionDigits:2,maximumFractionDigits:2});
function languageResult(){return EducationLanguages.calculatePair([{language:$('langName1').value,otherText:$('langOther1').value,points:n('lang1')},{language:$('langName2').value,otherText:$('langOther2').value,points:n('lang2')}]);}
function syncLanguageUI(){const s1=$('langName1'),s2=$('langName2');$('langOther1Wrap').classList.toggle('hidden',s1.value!=='other');$('langOther2Wrap').classList.toggle('hidden',s2.value!=='other');[s1,s2].forEach(s=>Array.from(s.options).forEach(o=>o.disabled=false));if(s1.value&&s1.value!=='other'){const o=Array.from(s2.options).find(x=>x.value===s1.value);if(o)o.disabled=true;}if(s2.value&&s2.value!=='other'){const o=Array.from(s1.options).find(x=>x.value===s2.value);if(o)o.disabled=true;}}
function trainingDatesSelection(){const selected=document.querySelector('input[name="trainingDates"]:checked');return selected?selected.value:'';}
function updateTrainingProofUI(){const proof=$('trainingProof'),status=$('trainingDatesStatus');if(!proof||!status)return;const active=$('training').checked;proof.classList.toggle('hidden',!active);if(!active)return;const value=trainingDatesSelection();status.className='training-proof-status '+(value==='yes'?'success':value==='no'?'warning':'neutral');if(value==='yes')status.textContent='✓ Οι ημερομηνίες έναρξης και λήξης αναγράφονται στο πιστοποιητικό.';else if(value==='no')status.textContent='⚠️ Απαιτείται πρόσθετη βεβαίωση από τον οικείο φορέα με την ημερομηνία έναρξης και λήξης.';else status.textContent='Έλεγξε το πιστοποιητικό πριν την υποβολή των δικαιολογητικών.';}
function trainingProofSummary(){if(!$('training').checked)return'';const value=trainingDatesSelection();if(value==='yes')return'Πιστοποιητικό σεμιναρίου: αναγράφονται ημερομηνία έναρξης και λήξης.';if(value==='no')return'ΔΙΚΑΙΟΛΟΓΗΤΙΚΟ: απαιτείται βεβαίωση φορέα με ημερομηνία έναρξης και λήξης του σεμιναρίου.';return'Έλεγχος πιστοποιητικού σεμιναρίου: εκκρεμεί ο έλεγχος ημερομηνίας έναρξης και λήξης.';}
function academic(){syncLanguageUI();const languages=languageResult();const grade=n('degreeGrade');const valid=$('degreeGrade').value!==''&&grade>=5&&grade<=10;const degree=valid?Math.round(grade*2.5*100)/100:0;const masters=n('masters')===1?20:n('masters')>=2?28:0;const raw=degree+($('secondDegree').checked?7:0)+($('phd').checked?40:0)+masters+languages.points+($('computer').checked?4:0)+($('training').checked?2:0);return{degree,raw,points:Math.min(raw,120),valid,masters,languages};}
function service(){const m=v=>Math.max(0,Math.floor(Number(v)||0));const tri=(v,rate,cap)=>({months:m(v),points:Math.min(m(v)*rate,cap)});const parts=[EducationService.regularPublic(n('publicMonths')),EducationService.difficult(n('hardMonths')),tri(n('covid2020'),1.5,10),tri(n('covid2021'),1.5,10),tri(n('covidHard2020'),3,20),tri(n('covidHard2021'),3,20)];const raw=parts.reduce((s,x)=>s+x.points,0),months=parts.reduce((s,x)=>s+x.months,0);return{raw,points:Math.min(raw,120),months};}
function social(){return EducationSocial.calculate({children:n('children'),candidateDisability:n('candidateDisability'),spouseDisability:n('spouseDisability'),childDisability:n('childDisability'),candidateMentalCondition:$('mental').checked,marriageYears4Plus:$('marriage4').checked});}
let eligibilityUiKey='';
function selectedEligibilityIds(){return Array.from(document.querySelectorAll('#licenseRequirements input[data-license-id]:checked')).map(x=>x.dataset.licenseId);}
function syncEligibilityUI(){const b=$('branch').value;const route=b==='PE25'?$('pe25Route').value:'';$('pe25RouteWrap').classList.toggle('hidden',b!=='PE25');const key=b+'|'+route;if(key===eligibilityUiKey)return;eligibilityUiKey=key;const host=$('licenseRequirements'),intro=$('licenseIntro');host.innerHTML='';if(!b){intro.textContent='Επίλεξε κλάδο για να εμφανιστούν τα απαιτούμενα πρόσθετα επαγγελματικά δικαιολογητικά.';return;}const req=EEPEligibility.getRequirements(b,route);if(req.routeRequired&&!req.route){intro.innerHTML='<strong>'+req.label+':</strong> '+req.note;return;}if(req.items.length===0){intro.innerHTML='<strong>'+req.label+':</strong> '+req.note;return;}intro.innerHTML='<strong>'+req.label+(req.routeLabel?' — '+req.routeLabel:'')+':</strong> έλεγξε ότι διαθέτεις όλα τα παρακάτω δικαιολογητικά.';req.items.forEach((item,i)=>{const row=document.createElement('div');row.className='checkrow';const id='licenseReq_'+i;row.innerHTML='<input type="checkbox" id="'+id+'" data-license-id="'+item.id+'"><label for="'+id+'">'+item.label+'<small>Υποχρεωτικό πρόσθετο δικαιολογητικό — δεν προσθέτει μόρια.</small></label>';host.appendChild(row);});}
function eligibility(){syncEligibilityUI();const b=$('branch').value,route=b==='PE25'?$('pe25Route').value:'';return EEPEligibility.evaluate(b,route,selectedEligibilityIds());}
function renderEligibility(){const e=eligibility(),box=$('licenseStatus'),side=$('licenseResult');box.className='priority';if(e.status==='unselected'){box.textContent='Δεν έχει επιλεγεί κλάδος.';side.textContent='—';}else if(e.status==='route-required'){box.textContent='ΠΕ25 — επίλεξε διαδρομή τίτλου για να ελεγχθούν τα σωστά δικαιολογητικά.';side.textContent='ΕΚΚΡΕΜΕΙ';}else if(e.status==='not-applicable'){box.className='priority yes';box.textContent='Δεν προβλέπεται ειδική άδεια/εγγραφή επαγγελματικού φορέα για τον επιλεγμένο κλάδο στην ενότητα «Άδειες και Βεβαιώσεις».';side.textContent='ΔΕΝ ΑΠΑΙΤΕΙΤΑΙ';}else if(e.complete){box.className='priority yes';box.textContent='✓ Δηλώθηκαν όλα τα απαιτούμενα πρόσθετα δικαιολογητικά ('+e.checked+'/'+e.required+').';side.textContent='ΠΛΗΡΗ';}else{box.className='priority';box.textContent='Λείπουν '+e.missing.length+' από '+e.required+' απαιτούμενα πρόσθετα δικαιολογητικά.';side.textContent='ΕΛΛΙΠΗ '+e.checked+'/'+e.required;}return e;}
function branchUI(){const b=$('branch').value,bc=b?b.replace(/^PE/,'ΠΕ'):'';const note=$('branchNote'),sn=$('serviceBranchNote');$('pe23Wrap').classList.toggle('hidden',b!=='PE23');$('formalMasterNote').classList.toggle('hidden',!['PE21','PE22','PE31'].includes(b));let t='Επίλεξε κλάδο για να εμφανιστούν οι ειδικές επισημάνσεις.';if(b==='PE23')t='<strong>ΠΕ23:</strong> η εξειδίκευση στη Σχολική Ψυχολογία δημιουργεί πρόταξη. Η Παιδαγωγική/Διδακτική Επάρκεια καθορίζει περαιτέρω τη σειρά μέσα στις ομάδες πρόταξης.';else if(b==='PE25')t='<strong>ΠΕ25:</strong> προϋπηρεσία αναπληρωτή εκπαιδευτικού ΠΕ87.02-Νοσηλευτικής που αποκτήθηκε με τις ειδικές διατάξεις της προκήρυξης προσμετράται και στον ΠΕ25.';else if(['PE21','PE22'].includes(b))t='<strong>'+bc+':</strong> όταν μεταπτυχιακός τίτλος αποτελεί τυπικό προσόν διορισμού, δεν μοριοδοτείται και η προϋπηρεσία προσμετράται μετά την κτήση του.';else if(b==='PE31')t='<strong>ΠΕ31:</strong> όταν μεταπτυχιακός τίτλος αποτελεί τυπικό προσόν διορισμού, δεν μοριοδοτείται και η προϋπηρεσία προσμετράται μετά την κτήση του. Επαγγελματική εμπειρία τριών ετών που αποτελεί τυπικό προσόν δεν μοριοδοτείται.';else if(b)t='Για τον '+bc+' εφαρμόζεται ο κοινός πίνακας μοριοδότησης ΕΕΠ. Η Παιδαγωγική/Διδακτική Επάρκεια αποτελεί κριτήριο πρόταξης.';note.innerHTML=t;let st='Η ειδική μοριοδότηση ιδιωτικής σχολικής προϋπηρεσίας με συντελεστή 0,9 δεν αφορά τα μέλη ΕΕΠ-ΕΒΠ.';if(b==='PE25')st+='<br><strong>ΠΕ25:</strong> έλεγξε και τυχόν επιλέξιμη προϋπηρεσία ΠΕ87.02-Νοσηλευτικής.';if(['PE21','PE22','PE31'].includes(b))st+='<br><strong>'+bc+':</strong> αν ο μεταπτυχιακός είναι τυπικό προσόν διορισμού, δήλωσε μόνο προϋπηρεσία μετά την κτήση του.';if(b==='PE31')st+='<br>Μην περιλάβεις την τριετή επαγγελματική εμπειρία όταν αυτή αποτελεί τυπικό προσόν διορισμού.';sn.innerHTML=st;$('schoolPsychReminder').classList.toggle('hidden',!(b==='PE23'&&$('schoolPsych').value==='degree'));syncEligibilityUI();}
function priority(){const b=$('branch').value,ped=$('pedagogical').checked,pb=$('priorityBox');pb.className='priority';if(!b){pb.textContent='Επίλεξε κλάδο για έλεγχο πρόταξης';}else if(b==='PE23'){const spec=$('schoolPsych').value!=='none';pb.className='priority '+(spec?'special':ped?'yes':'');if(spec&&ped)pb.textContent='ΠΕ23 — Ομάδα πρόταξης 1: εξειδίκευση Σχολικής Ψυχολογίας + ΠΔΕ';else if(spec)pb.textContent='ΠΕ23 — Ομάδα πρόταξης 2: εξειδίκευση Σχολικής Ψυχολογίας χωρίς ΠΔΕ';else if(ped)pb.textContent='ΠΕ23 — Ομάδα πρόταξης 3: χωρίς εξειδίκευση, με ΠΔΕ';else pb.textContent='ΠΕ23 — Ομάδα 4: χωρίς εξειδίκευση και χωρίς ΠΔΕ';}else{pb.className='priority'+(ped?' yes':'');pb.textContent=ped?'Πρόταξη λόγω Παιδαγωγικής και Διδακτικής Επάρκειας':'Χωρίς δηλωμένη πρόταξη Παιδαγωγικής/Διδακτικής Επάρκειας';}const sp=$('specialPriorityBox');const extras=[];if($('braille').checked)extras.push('Braille — προτεραιότητα για μαθητές με προβλήματα όρασης');if($('signLanguage').checked)extras.push('ΕΝΓ — προτεραιότητα για κωφούς/βαρήκοους μαθητές');sp.textContent=extras.join(' · ');sp.className='priority special'+(extras.length?'':' hidden');}
function render(){updateTrainingProofUI();branchUI();const a=academic(),s=service(),c=social(),total=a.points+s.points+c.total;const lw=$('languageWarning');lw.textContent=a.languages.warnings.join(' ');lw.classList.toggle('hidden',a.languages.warnings.length===0);$('gradeWarning').classList.toggle('hidden',$('degreeGrade').value===''||a.valid);$('academicSubtotal').textContent=fmt(a.points);$('serviceSubtotal').textContent=fmt(s.points);$('socialSubtotal').textContent=fmt(c.total);$('totalPoints').textContent=fmt(total);$('degreePoints').textContent=fmt(a.degree);$('academicPoints').textContent=fmt(a.points)+(a.raw>120?' (όριο 120)':'');$('servicePoints').textContent=fmt(s.points)+(s.raw>120?' (όριο 120)':'');$('socialPoints').textContent=fmt(c.total);const sw=$('serviceWarning');const msgs=[];if(s.months>120)msgs.push('Έχουν δηλωθεί '+s.months+' μήνες σε ξεχωριστές κατηγορίες. Έλεγξε ότι δεν έχει δηλωθεί ο ίδιος μήνας δύο φορές και ότι η συνολική πραγματική προϋπηρεσία δεν υπερβαίνει τους 120 μήνες που λαμβάνονται υπόψη.');if(s.raw>120)msgs.push('Η μοριοδότηση προϋπηρεσίας περιορίστηκε στο ανώτατο όριο των 120 μορίων.');sw.textContent=msgs.join(' ');sw.classList.toggle('hidden',msgs.length===0);const soc=$('socialWarning');soc.textContent=c.warnings.join(' ');soc.classList.toggle('hidden',c.warnings.length===0);priority();const e=renderEligibility();return{a,s,c,e,total};}
function summary(r){const branch=$('branch'),branchText=branch.value?branch.options[branch.selectedIndex].textContent.trim():'κλάδος μη επιλεγμένος';return[`Υπολογισμός μορίων 2ΕΑ/2025 — ${branchText}`,`Βαθμός πτυχίου: ${fmt(r.a.degree)}`,`Ακαδημαϊκά: ${fmt(r.a.points)}`,`Προϋπηρεσία: ${fmt(r.s.points)}`,`Κοινωνικά: ${fmt(r.c.total)}`,`ΣΥΝΟΛΟ: ${fmt(r.total)}`,`Άδειες/βεβαιώσεις: ${$('licenseResult').textContent}`,`Πρόταξη: ${$('priorityBox').textContent}${$('specialPriorityBox').classList.contains('hidden')?'':'\nΕιδική προτεραιότητα: '+$('specialPriorityBox').textContent}`,trainingProofSummary()].filter(Boolean).join('\n');}
document.addEventListener('input',render);document.addEventListener('change',render);$('copyBtn').addEventListener('click',async()=>{const txt=summary(render());try{await navigator.clipboard.writeText(txt);$('copyBtn').textContent='Αντιγράφηκε';setTimeout(()=>$('copyBtn').textContent='Αντιγραφή',1200)}catch(e){alert(txt)}});$('resetBtn').addEventListener('click',()=>{document.querySelectorAll('input[type=number]').forEach(x=>x.value=x.id==='degreeGrade'?'':'0');document.querySelectorAll('input[type=text]').forEach(x=>x.value='');document.querySelectorAll('input[type=checkbox]').forEach(x=>x.checked=false);document.querySelectorAll('input[name="trainingDates"]').forEach(x=>x.checked=false);document.querySelectorAll('select').forEach(x=>x.selectedIndex=0);eligibilityUiKey='';render();});render();})();
</script>
<?php require_once __DIR__ . '/includes/footer.php'; ?>
  <script src="assets/common.js?v=3.20.9"></script>
</body>
</html>
