<!doctype html>
<html lang="el">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Υπολογισμός μορίων απόσπασης εκπαιδευτικών στα Ευρωπαϊκά Σχολεία με βάση την πρόσκληση 33598/Η2/18-3-2026.">
<title>Μόρια Απόσπασης σε Ευρωπαϊκά Σχολεία</title>
<link rel="stylesheet" href="assets/common.css?v=3.20.9-b1">
</head>
<body class="edu-ui edu-page-european-schools">
<main class="page-shell">
<?php require_once __DIR__ . '/includes/header.php'; ?>
<section class="hero">
<h1>Μόρια Απόσπασης σε Ευρωπαϊκά Σχολεία</h1>
<p>Υπολόγισε τα μόρια τυπικών προσόντων και διδακτικής εμπειρίας πριν από τη συνέντευξη και, όταν είναι διαθέσιμες οι βαθμολογίες της προφορικής διαδικασίας, το τελικό σύνολο.</p>
<div class="hero-meta"><span>Α + Β: έως 50</span><span>Συνέντευξη: έως 40</span><span>Τελικό: έως 90</span><span>Πρόσκληση 33598/Η2/18-3-2026</span></div>
</section>
<div class="layout"><div>
<section class="card">
<h2>1. Θέση & βασικές προϋποθέσεις</h2>
<p class="subtitle">Επίλεξε τη θέση που σε ενδιαφέρει. Ο κλάδος προκύπτει αυτόματα· μόνο όταν μία θέση δέχεται περισσότερους κλάδους θα σου ζητηθεί να επιλέξεις μεταξύ αυτών.</p>
<div class="field-grid">
<div class="field full"><label for="position">Θέση της πρόσκλησης 2026<small>Η θέση καθορίζει αυτόματα τον κλάδο. Αν προβλέπονται περισσότεροι κλάδοι, εμφανίζεται μόνο τότε μια σύντομη επιλογή μεταξύ αυτών.</small></label><select id="position"><option value="">— Επίλεξε θέση —</option><option value="pe70_lux2">ΠΕ70 — Ε.Σ. Λουξεμβούργο II</option><option value="pe70_bru3">ΠΕ70 — Ε.Σ. Βρυξέλλες III</option><option value="pe06_bru1">ΠΕ06 — Ε.Σ. Βρυξέλλες I</option><option value="pe06_mol">ΠΕ06 — Ε.Σ. MOL</option><option value="pe02_bru3">ΠΕ02 — Ε.Σ. Βρυξέλλες III</option><option value="history_bru1">Ιστορία (ΠΕ02 ή ΠΕ33) — Ε.Σ. Βρυξέλλες I</option><option value="pe03_bru3">ΠΕ03 — Ε.Σ. Βρυξέλλες III</option><option value="chemistry_bru3">Χημεία (ΠΕ04.02 ή ΠΕ85) — Ε.Σ. Βρυξέλλες III</option><option value="biology_bru3">ΠΕ04.04 — Ε.Σ. Βρυξέλλες III</option><option value="pe08_mol">ΠΕ08 — Ε.Σ. MOL</option><option value="pe11_bru3">ΠΕ11 — Ε.Σ. Βρυξέλλες III</option><option value="librarian_lux2">EL & EN Librarian — Ε.Σ. Λουξεμβούργο II</option></select><div id="positionBranchInfo" class="info hidden edu-mt-10"></div><div id="branchChoiceWrap" class="hidden edu-mt-12"><label for="selectedBranch">Ο κλάδος μου<small>Η θέση δέχεται περισσότερους από έναν κλάδους. Επίλεξε μόνο μεταξύ των κλάδων που προβλέπει η πρόσκληση.</small></label><select id="selectedBranch"><option value="">— Επίλεξε κλάδο —</option></select></div></div>
<div class="field"><label>Συνολική αναγνωρισμένη διδακτική υπηρεσία<small>Όπως στο Φύλλο Μητρώου: έτη, μήνες και ημέρες. Απαιτούνται τουλάχιστον 4 πλήρη έτη· κάθε πλήρες επιπλέον έτος δίνει 1 μονάδα, έως 9.</small></label><div class="duration-grid"><div><span class="mini-label">Έτη</span><input type="number" id="teachingYears" min="0" step="1" inputmode="numeric" value="" placeholder="π.χ. 12"></div><div><span class="mini-label">Μήνες</span><input type="number" id="teachingMonths" min="0" max="11" step="1" inputmode="numeric" value="" placeholder="0–11"></div><div><span class="mini-label">Ημέρες</span><input type="number" id="teachingDays" min="0" max="31" step="1" inputmode="numeric" value="" placeholder="0–31"></div></div><div id="teachingDurationHint" class="subtitle edu-m-8-0-0"></div></div>
<div class="field"><label for="ictLevel">Πιστοποιημένη γνώση ΤΠΕ<small>Απαιτείται τουλάχιστον Α΄ επίπεδο. Το Β΄ επίπεδο δίνει 2 μονάδες.</small></label><select id="ictLevel"><option value="">— Επίλεξε —</option><option value="none">Δεν διαθέτω Α΄ επίπεδο</option><option value="a">Α΄ επίπεδο — προϋπόθεση, 0 μόρια</option><option value="b">Β΄ επίπεδο — 2 μόρια</option></select></div>
<div class="field"><label for="blockingIssue">Κώλυμα συμμετοχής / επιλογής</label><select id="blockingIssue"><option value="">— Επίλεξε —</option><option value="no">Όχι</option><option value="yes">Ναι / πιθανόν</option></select></div>
</div>
<div id="positionRequirementWrap" class="field hidden edu-mt-13"><label for="positionLanguageRequirementMet" id="positionRequirementLabel">Γλωσσική προϋπόθεση θέσης</label><select id="positionLanguageRequirementMet"><option value="">— Επίλεξε —</option><option value="yes">Ναι, την καλύπτω</option><option value="no">Όχι</option></select></div>
<div id="librarianWrap" class="field hidden edu-mt-13"><label for="librarianQualification">Διαθέτω το προβλεπόμενο προσόν Βιβλιοθηκονομίας;</label><select id="librarianQualification"><option value="">— Επίλεξε —</option><option value="yes">Ναι</option><option value="no">Όχι</option></select></div>
<details><summary>Ειδικές γλωσσικές απαιτήσεις θέσεων 2026</summary><ul class="criteria"><li>ΠΕ70 Λουξεμβούργο II / Βρυξέλλες III, ΠΕ02 Βρυξέλλες III, ΠΕ03, Χημεία, Βιολογία και ΠΕ11 Βρυξέλλες III: Γ2 σε Αγγλικά, Γαλλικά ή Γερμανικά.</li><li>Ιστορία Βρυξέλλες I και ΠΕ08 MOL: Γ2 Αγγλικά.</li><li>Librarian Λουξεμβούργο II: προσόν Βιβλιοθηκονομίας και Γ2 Αγγλικά.</li></ul></details>
</section>
<section class="card">
<h2>2. Α. Επιστημονική & παιδαγωγική κατάρτιση</h2>
<div class="check"><input type="checkbox" id="phd"><label for="phd">Διδακτορικό δίπλωμα <small>5 μονάδες</small></label></div><div class="check"><input type="checkbox" id="master"><label for="master">Μεταπτυχιακό δίπλωμα ειδίκευσης <small>3 μονάδες</small></label></div><div class="check"><input type="checkbox" id="secondPhd"><label for="secondPhd">Δεύτερο διδακτορικό <small>3 μονάδες</small></label></div><div class="check"><input type="checkbox" id="secondMaster"><label for="secondMaster">Δεύτερο μεταπτυχιακό <small>1 μονάδα</small></label></div><div class="check"><input type="checkbox" id="secondDegree"><label for="secondDegree">Δεύτερο πανεπιστημιακό πτυχίο <small>2 μονάδες</small></label></div><div class="check"><input type="checkbox" id="retrainingDegree"><label for="retrainingDegree">Τίτλος Διδασκαλείου μετεκπαίδευσης <small>2 μονάδες</small></label></div>
<h3>Γλωσσομάθεια</h3>
<div class="field-grid">
<div class="field"><label for="hostLanguageKey">Επίσημη γλώσσα χώρας έδρας<small id="hostLanguageHint">Επίλεξε πρώτα θέση για να εμφανιστούν μόνο οι επίσημες γλώσσες της χώρας.</small></label><select id="hostLanguageKey"><option value="">— Επίλεξε θέση πρώτα —</option></select></div>
<div class="field"><label for="hostLanguageLevel">Επίπεδο επίσημης γλώσσας<small>Γ2: 5 · Γ1: 4 · Β2: 2,5</small></label><select id="hostLanguageLevel"><option value="none">Δεν δηλώνω</option><option value="b2">Β2 — 2,5</option><option value="c1">Γ1 — 4</option><option value="c2">Γ2 — 5</option></select></div>
<div class="field"><label for="secondWorkingLanguage">Δεύτερη γλώσσα εργασίας<small>Μόνο Αγγλικά / Γαλλικά / Γερμανικά και όχι γλώσσα που έχει ήδη δηλωθεί.</small></label><select id="secondWorkingLanguage"><option value="">Δεν δηλώνω</option></select></div>
<div class="field"><label for="secondWorkingLevel">Επίπεδο δεύτερης γλώσσας<small>Γ2: 4 · Γ1: 3 · Β2: 1,5</small></label><select id="secondWorkingLevel"><option value="none">Δεν δηλώνω</option><option value="b2">Β2 — 1,5</option><option value="c1">Γ1 — 3</option><option value="c2">Γ2 — 4</option></select></div>
<div class="field"><label for="thirdWorkingLanguage">Τρίτη γλώσσα εργασίας<small>Μόνο Αγγλικά / Γαλλικά / Γερμανικά και διαφορετική από τις προηγούμενες.</small></label><select id="thirdWorkingLanguage"><option value="">Δεν δηλώνω</option></select></div>
<div class="field"><label for="thirdWorkingLevel">Επίπεδο τρίτης γλώσσας<small>Γ2: 3 · Γ1: 2 · Β2: 1</small></label><select id="thirdWorkingLevel"><option value="none">Δεν δηλώνω</option><option value="b2">Β2 — 1</option><option value="c1">Γ1 — 2</option><option value="c2">Γ2 — 3</option></select></div>
<div class="field"><label for="otherEULanguage">Άλλη γλώσσα της Ε.Ε.<small>Επιλέγονται μόνο λοιπές επίσημες γλώσσες της Ε.Ε. και αποκλείεται αυτόματα όποια έχει δηλωθεί ήδη.</small></label><select id="otherEULanguage"><option value="">Δεν δηλώνω</option></select></div><div class="field"><label for="otherEULevel">Επίπεδο άλλης γλώσσας Ε.Ε.<small>Γ2: 2 · Γ1: 1 · Β2: 0,5</small></label><select id="otherEULevel"><option value="none">Δεν δηλώνω</option><option value="b2">Β2 — 0,5</option><option value="c1">Γ1 — 1</option><option value="c2">Γ2 — 2</option></select></div>
</div><div class="note"><strong>Αυτόματος έλεγχος γλωσσών:</strong> η χώρα της θέσης περιορίζει τις διαθέσιμες επίσημες γλώσσες και η ίδια γλώσσα δεν μπορεί να μοριοδοτηθεί δεύτερη φορά σε άλλη κατηγορία.</div><div class="subtot"><span>Σύνολο Α</span><span class="pill" id="academicSubtotal">0 / 32</span></div>
</section>
<section class="card">
<h2>3. Β. Υπηρεσιακή κατάσταση & διδακτική εμπειρία</h2>
<div class="field-grid"><div class="field"><label for="higherEducationSemesters">Ακαδημαϊκά εξάμηνα αυτοδύναμου διδακτικού έργου σε ΑΕΙ<small>0,50 ανά εξάμηνο · έως 2.</small></label><input type="number" id="higherEducationSemesters" min="0" step="1" value="0"></div><div class="field"><label for="innovativePrograms">Καινοτόμα ευρωπαϊκά / διεθνή προγράμματα<small>1 ανά πρόγραμμα · έως 3.</small></label><input type="number" id="innovativePrograms" min="0" step="1" value="0"></div></div>
<h3>Επιμόρφωση — έως 4 μονάδες</h3><div class="check"><input type="checkbox" id="annualTraining"><label for="annualTraining">Ετήσια επιμόρφωση ΣΕΛΜΕ/ΣΕΛΔΕ/ΑΣΠΑΙΤΕ/ΣΕΛΕΤΕ, εφόσον δεν αποτέλεσε προσόν διορισμού <small>1 μονάδα</small></label></div>
<div class="field-grid edu-mt-10"><div class="field"><label for="universityTrainingCount">Προγράμματα ΑΕΙ ≥300 ωρών ή ≥9 μηνών<small>1 ανά πρόγραμμα · έως 2.</small></label><input type="number" id="universityTrainingCount" min="0" step="1" value="0"></div><div class="field"><label for="ministryTrainingHours">Ώρες ΠΕΚΕΣ/ΠΕΚ/ΙΕΠ/ΠΙ/ΟΕΠΕΚ/ΥΠΑΙΘ<small>0,10 ανά 10 ώρες · έως 1.</small></label><input type="number" id="ministryTrainingHours" min="0" step="1" value="0"></div><div class="field"><label for="publicAdminTrainingHours">Ώρες ΕΚΔΔΑ / ΙΠΕΜ-ΔΟΕ / ΚΕΜΕΤΕ-ΟΛΜΕ<small>0,10 ανά 10 ώρες · έως 1.</small></label><input type="number" id="publicAdminTrainingHours" min="0" step="1" value="0"></div><div class="field"><label for="eapAnnualUnits">Ετήσιες θεματικές ενότητες ΕΑΠ</label><input type="number" id="eapAnnualUnits" min="0" step="1" value="0"></div><div class="field"><label for="eapSemesterUnits">Εξαμηνιαίες θεματικές ενότητες ΕΑΠ</label><input type="number" id="eapSemesterUnits" min="0" step="1" value="0"></div></div><div class="check"><input type="checkbox" id="majorTraining"><label for="majorTraining">Μείζον Πρόγραμμα Επιμόρφωσης ή κατάλογος επιμορφωτών Α΄/Β΄ επιπέδου <small>1 μονάδα</small></label></div><div class="subtot"><span>Σύνολο Β</span><span class="pill" id="serviceSubtotal">0 / 18</span></div>
</section>
<section class="card">
<h2>4. Δυναμικό checklist δικαιολογητικών</h2><p class="subtitle">Η λίστα προσαρμόζεται στα προσόντα και στις επιλογές που δηλώνεις παραπάνω. Δεν υποκαθιστά τον τελικό έλεγχο της επίσημης πρόσκλησης.</p><ul id="documentsChecklist" class="document-checklist"></ul><div class="note">Η πρόσκληση απαιτεί τα δηλούμενα δικαιολογητικά να έχουν αναρτηθεί πριν από την οριστική καταχώριση της αίτησης.</div>
</section>
<section class="card">
<h2>5. Γ. Προφορική εξέταση & συνέντευξη</h2><p class="subtitle">Συμπλήρωσέ τα μόνο όταν γνωρίζεις τις βαθμολογίες. Η βάση στην προαπαιτούμενη ξένη γλώσσα είναι 5/10.</p>
<div class="field-grid"><div class="field"><label for="oralPrerequisiteLanguage">Προαπαιτούμενη ξένη γλώσσα — προφορικός λόγος<small>0–10 · βάση 5.</small></label><input type="number" id="oralPrerequisiteLanguage" min="0" max="10" step="0.1" value="" placeholder="0–10"></div><div class="field"><label for="oralWorkingLanguage1">Άλλη γλώσσα εργασίας 1<small>0–5.</small></label><input type="number" id="oralWorkingLanguage1" min="0" max="5" step="0.1" value="" placeholder="0–5"></div><div class="field"><label for="oralWorkingLanguage2">Άλλη γλώσσα εργασίας 2<small>0–5.</small></label><input type="number" id="oralWorkingLanguage2" min="0" max="5" step="0.1" value="" placeholder="0–5"></div><div class="field"><label for="thoughtSpeech">Συγκρότηση σκέψης & λόγου<small>0–5.</small></label><input type="number" id="thoughtSpeech" min="0" max="5" step="0.1" value="" placeholder="0–5"></div><div class="field"><label for="interculturalInnovation">Έκφραση, διαπολιτισμική επικοινωνία & καινοτόμες δράσεις<small>0–5.</small></label><input type="number" id="interculturalInnovation" min="0" max="5" step="0.1" value="" placeholder="0–5"></div><div class="field"><label for="curriculumKnowledge">Ενημέρωση & γνώση προγράμματος σπουδών Ευρωπαϊκών Σχολείων<small>0–10.</small></label><input type="number" id="curriculumKnowledge" min="0" max="10" step="0.1" value="" placeholder="0–10"></div></div>
<div class="note">Στη συνέντευξη καλείται το 50% των υποψηφίων με τα υψηλότερα μόρια του 1ου σταδίου, με στρογγυλοποίηση στην πλησιέστερη ακέραιη μονάδα και αριθμό τουλάχιστον τριπλάσιο των θέσεων. Δεν υπάρχει σταθερό όριο μορίων.</div><div class="subtot"><span>Σύνολο Γ</span><span class="pill" id="interviewSubtotal">— / 40</span></div>
</section>
</div>
<aside class="card results" aria-live="polite"><h2>Αποτέλεσμα</h2><div class="stage"><div class="stage-label">1ο στάδιο · πριν τη συνέντευξη</div><div class="stage-number"><span id="preInterviewTotal">0</span> <small class="edu-stage-suffix">/ 50</small></div></div><div class="result-row"><span>Α. Κατάρτιση</span><strong id="academicResult">0 / 32</strong></div><div class="result-row"><span>Β. Υπηρεσία / εμπειρία</span><strong id="serviceResult">0 / 18</strong></div><div class="result-row"><span>Γ. Συνέντευξη</span><strong id="interviewResult">— / 40</strong></div><details class="breakdown-box"><summary>Αναλυτική κατανομή μορίων</summary><div id="academicBreakdown" class="breakdown-list"></div><div id="serviceBreakdown" class="breakdown-list"></div></details><div class="stage"><div class="stage-label">Τελική βαθμολογία</div><div class="stage-number final" id="finalTotal">—</div><div id="finalHelp" class="edu-small-muted">Συμπλήρωσε όλα τα πεδία της συνέντευξης για τελικό /90.</div></div><div id="eligibilityStatus" role="status" aria-live="polite"></div><div class="actions"><button type="button" class="primary" id="copyBtn">Αντιγραφή σύνοψης</button><button type="button" class="secondary" id="resetBtn">Μηδενισμός</button></div></aside>
</div>
<div class="source-note"><strong>Πηγές / Νομική βάση:</strong><br><strong>Πηγή:</strong> Πρόσκληση 33598/Η2/18-03-2026 για απόσπαση εκπαιδευτικών στα Ευρωπαϊκά Σχολεία και η αναφερόμενη Υ.Α. 26754/Η2/10-03-2022 (Β΄1165, διόρθωση Β΄1300). Το εργαλείο είναι ενημερωτικό.</div>
<?php require_once __DIR__ . '/includes/footer.php'; ?>
</main>
<script src="includes/european-schools-calculations.js"></script>
<script>
(function(){'use strict';
const $=id=>document.getElementById(id),fmt=n=>Number(n||0).toLocaleString('el-GR',{maximumFractionDigits:2});
const ids=['position','selectedBranch','teachingYears','teachingMonths','teachingDays','ictLevel','blockingIssue','positionLanguageRequirementMet','librarianQualification','phd','master','secondPhd','secondMaster','secondDegree','retrainingDegree','hostLanguageKey','hostLanguageLevel','secondWorkingLanguage','secondWorkingLevel','thirdWorkingLanguage','thirdWorkingLevel','otherEULanguage','otherEULevel','higherEducationSemesters','innovativePrograms','annualTraining','universityTrainingCount','ministryTrainingHours','publicAdminTrainingHours','eapAnnualUnits','eapSemesterUnits','majorTraining','oralPrerequisiteLanguage','oralWorkingLanguage1','oralWorkingLanguage2','thoughtSpeech','interculturalInnovation','curriculumKnowledge'];
function normalize(){['teachingYears','higherEducationSemesters','innovativePrograms','universityTrainingCount','ministryTrainingHours','publicAdminTrainingHours','eapAnnualUnits','eapSemesterUnits'].forEach(id=>{const e=$(id);if(e.value!=='')e.value=String(Math.max(0,Math.floor(Number(e.value)||0)));});if($('teachingMonths').value!=='')$('teachingMonths').value=String(Math.min(11,Math.max(0,Math.floor(Number($('teachingMonths').value)||0))));if($('teachingDays').value!=='')$('teachingDays').value=String(Math.min(31,Math.max(0,Math.floor(Number($('teachingDays').value)||0))));}
function normalizeBranchLabel(value){return String(value||'').replace(/^PE(?=\d)/,'ΠΕ').replace(/^PΕ(?=\d)/,'ΠΕ').replace(/^ΠE(?=\d)/,'ΠΕ');}
function normalizeVisibleBranchLabels(){document.querySelectorAll('#position option').forEach(o=>{o.textContent=o.textContent.replace(/\bPE(?=\d)/g,'ΠΕ').replace(/\bPΕ(?=\d)/g,'ΠΕ').replace(/\bΠE(?=\d)/g,'ΠΕ');});}
function languageLabel(key){return EuropeanSchools.LANGUAGE_LABELS[key]||key||'—'}
function fillSelect(select,items,placeholder,current){select.innerHTML='<option value="">'+placeholder+'</option>'+items.map(key=>'<option value="'+key+'">'+languageLabel(key)+'</option>').join('');if(items.includes(current))select.value=current;else select.value='';}
function refreshLanguageUI(p){
  const host=$('hostLanguageKey'),second=$('secondWorkingLanguage'),third=$('thirdWorkingLanguage'),other=$('otherEULanguage');
  let hostVal=host.value,secondVal=second.value,thirdVal=third.value,otherVal=other.value;
  const hostAllowed=p&&p.hostCountry?(EuropeanSchools.HOST_LANGUAGES[p.hostCountry]||[]):[];
  fillSelect(host,hostAllowed,p?'— Δεν δηλώνω —':'— Επίλεξε θέση πρώτα —',hostVal);
  hostVal=host.value;
  if(secondVal===hostVal)secondVal='';
  if(thirdVal===hostVal||thirdVal===secondVal)thirdVal='';
  const secondAllowed=EuropeanSchools.WORKING_LANGUAGES.filter(k=>k!==hostVal&&k!==thirdVal);
  fillSelect(second,secondAllowed,'Δεν δηλώνω',secondVal);secondVal=second.value;
  const thirdAllowed=EuropeanSchools.WORKING_LANGUAGES.filter(k=>k!==hostVal&&k!==secondVal);
  fillSelect(third,thirdAllowed,'Δεν δηλώνω',thirdVal);thirdVal=third.value;
  const used=new Set([hostVal,secondVal,thirdVal].filter(Boolean));
  const otherAllowed=EuropeanSchools.OTHER_EU_LANGUAGES.filter(k=>!used.has(k));
  fillSelect(other,otherAllowed,'Δεν δηλώνω',otherVal);
  if(p&&p.hostCountry==='belgium')$('hostLanguageHint').textContent='Βέλγιο: Ολλανδικά, Γαλλικά ή Γερμανικά.';
  else if(p&&p.hostCountry==='luxembourg')$('hostLanguageHint').textContent='Λουξεμβούργο: Γαλλικά, Γερμανικά ή Λουξεμβουργιανά.';
  else $('hostLanguageHint').textContent='Επίλεξε πρώτα θέση για να εμφανιστούν μόνο οι επίσημες γλώσσες της χώρας.';
}
function updatePositionUI(){
  const p=EuropeanSchools.POSITIONS_2026[$('position').value],needs=p&&(p.requirement==='working_c2'||p.requirement==='english_c2'),info=$('positionBranchInfo'),choiceWrap=$('branchChoiceWrap'),branchSelect=$('selectedBranch');
  $('positionRequirementWrap').classList.toggle('hidden',!needs);$('librarianWrap').classList.toggle('hidden',!(p&&p.librarian));
  if(p){info.classList.remove('hidden');if(p.librarian){info.innerHTML='<strong>Κλάδοι θέσης:</strong> κλάδοι Δευτεροβάθμιας Εκπαίδευσης, με το προβλεπόμενο προσόν Βιβλιοθηκονομίας.';choiceWrap.classList.add('hidden');branchSelect.innerHTML='<option value="">— Επίλεξε κλάδο —</option>';branchSelect.value='';}else if(p.branches.length===1){const branch=normalizeBranchLabel(p.branches[0]);info.innerHTML='<strong>Κλάδος θέσης:</strong> '+branch;choiceWrap.classList.add('hidden');branchSelect.innerHTML='<option value="">— Επίλεξε κλάδο —</option>';branchSelect.value='';}else{const previous=branchSelect.value;info.innerHTML='<strong>Επιλέξιμοι κλάδοι:</strong> '+p.branches.map(normalizeBranchLabel).join(' ή ');branchSelect.innerHTML='<option value="">— Επίλεξε κλάδο —</option>'+p.branches.map(b=>'<option value="'+b+'">'+normalizeBranchLabel(b)+'</option>').join('');if(p.branches.includes(previous))branchSelect.value=previous;choiceWrap.classList.remove('hidden');}}else{info.classList.add('hidden');info.innerHTML='';choiceWrap.classList.add('hidden');branchSelect.innerHTML='<option value="">— Επίλεξε κλάδο —</option>';branchSelect.value='';}
  if(needs)$('positionRequirementLabel').textContent=p.requirement==='english_c2'?'Καλύπτω την απαίτηση Γ2 στην αγγλική γλώσσα;':'Καλύπτω την απαίτηση Γ2 σε μία γλώσσα εργασίας (Αγγλικά / Γαλλικά / Γερμανικά);';else $('positionLanguageRequirementMet').value='';
  if(!(p&&p.librarian))$('librarianQualification').value='';refreshLanguageUI(p);
}
function v(id){return $(id).value}function c(id){return $(id).checked}
function options(){normalize();return{position:v('position'),selectedBranch:v('selectedBranch'),teachingYears:v('teachingYears'),teachingMonths:v('teachingMonths'),teachingDays:v('teachingDays'),ictLevel:v('ictLevel'),blockingIssue:v('blockingIssue'),positionLanguageRequirementMet:v('positionLanguageRequirementMet'),librarianQualification:v('librarianQualification'),phd:c('phd'),master:c('master'),secondPhd:c('secondPhd'),secondMaster:c('secondMaster'),secondDegree:c('secondDegree'),retrainingDegree:c('retrainingDegree'),hostLanguageKey:v('hostLanguageKey'),hostLanguageLevel:v('hostLanguageLevel'),secondWorkingLanguage:v('secondWorkingLanguage'),secondWorkingLevel:v('secondWorkingLevel'),thirdWorkingLanguage:v('thirdWorkingLanguage'),thirdWorkingLevel:v('thirdWorkingLevel'),otherEULanguage:v('otherEULanguage'),otherEULevel:v('otherEULevel'),higherEducationSemesters:v('higherEducationSemesters'),innovativePrograms:v('innovativePrograms'),annualTraining:c('annualTraining'),universityTrainingCount:v('universityTrainingCount'),ministryTrainingHours:v('ministryTrainingHours'),publicAdminTrainingHours:v('publicAdminTrainingHours'),eapAnnualUnits:v('eapAnnualUnits'),eapSemesterUnits:v('eapSemesterUnits'),majorTraining:c('majorTraining'),oralPrerequisiteLanguage:v('oralPrerequisiteLanguage'),oralWorkingLanguage1:v('oralWorkingLanguage1'),oralWorkingLanguage2:v('oralWorkingLanguage2'),thoughtSpeech:v('thoughtSpeech'),interculturalInnovation:v('interculturalInnovation'),curriculumKnowledge:v('curriculumKnowledge')}}
function breakRows(items){return items.map(([label,points])=>'<div class="break-row"><span>'+label+'</span><strong>'+fmt(points)+'</strong></div>').join('')}
function renderBreakdown(r){
 const a=[],tb=r.academic.titleBreakdown;
 if(tb.phd)a.push(['Διδακτορικό',tb.phd]);if(tb.master)a.push(['Μεταπτυχιακό',tb.master]);if(tb.secondPhd)a.push(['2ο διδακτορικό',tb.secondPhd]);if(tb.secondMaster)a.push(['2ο μεταπτυχιακό',tb.secondMaster]);if(tb.secondDegree)a.push(['2ο πτυχίο',tb.secondDegree]);if(tb.retrainingDegree)a.push(['Διδασκαλείο μετεκπαίδευσης',tb.retrainingDegree]);
 a.push(['Επίσημη γλώσσα'+(v('hostLanguageKey')?' ('+languageLabel(v('hostLanguageKey'))+')':''),r.academic.hostLanguage],['2η γλώσσα εργασίας'+(v('secondWorkingLanguage')?' ('+languageLabel(v('secondWorkingLanguage'))+')':''),r.academic.secondWorkingLanguage],['3η γλώσσα εργασίας'+(v('thirdWorkingLanguage')?' ('+languageLabel(v('thirdWorkingLanguage'))+')':''),r.academic.thirdWorkingLanguage],['Άλλη γλώσσα Ε.Ε.'+(v('otherEULanguage')?' ('+languageLabel(v('otherEULanguage'))+')':''),r.academic.otherEULanguage],['ΤΠΕ Β΄ επιπέδου',r.academic.ict]);
 $('academicBreakdown').innerHTML='<div class="stage-label">Α. Κατάρτιση</div>'+breakRows(a);
 $('serviceBreakdown').innerHTML='<div class="stage-label edu-mt-8">Β. Υπηρεσία / εμπειρία</div>'+breakRows([['Πλήρη έτη πέρα από την τετραετία',r.service.extraTeachingYears],['Αυτοδύναμο έργο σε ΑΕΙ',r.service.higherEducation],['Καινοτόμα προγράμματα / δράσεις',r.service.innovation],['Επιμόρφωση',r.service.training]]);
}
function renderDocuments(r){$('documentsChecklist').innerHTML=r.documents.map(d=>'<li><span class="doc-mark">✓</span><span>'+d.text+'</span></li>').join('')}
function renderDuration(r){const d=r.service.duration;$('teachingDurationHint').textContent=(v('teachingYears')===''?'Δεν έχει δηλωθεί ακόμη υπηρεσία.':('Καταχωρισμένη υπηρεσία: '+d.years+' έτη, '+d.months+' μήνες, '+d.days+' ημέρες · μοριοδοτούνται μόνο τα πλήρη έτη πέρα από την τετραετία.'));}
function calculate(){updatePositionUI();const r=EuropeanSchools.calculate(options());$('academicSubtotal').textContent=fmt(r.academic.total)+' / 32';$('serviceSubtotal').textContent=fmt(r.service.total)+' / 18';$('preInterviewTotal').textContent=fmt(r.preInterview);$('academicResult').textContent=fmt(r.academic.total)+' / 32';$('serviceResult').textContent=fmt(r.service.total)+' / 18';renderBreakdown(r);renderDocuments(r);renderDuration(r);
 if(r.interview.prerequisiteEntered&&!r.interview.languageBasePassed){$('interviewSubtotal').textContent=fmt(r.interview.total)+' / 40';$('interviewResult').textContent=fmt(r.interview.total)+' / 40';$('finalTotal').textContent='—';$('finalHelp').textContent='Δεν επιτεύχθηκε η βάση 5/10 στην προαπαιτούμενη ξένη γλώσσα — δεν προκύπτει τελικό /90.';}else if(r.interview.complete){$('interviewSubtotal').textContent=fmt(r.interview.total)+' / 40';$('interviewResult').textContent=fmt(r.interview.total)+' / 40';$('finalTotal').textContent=fmt(r.finalTotal)+' / 90';$('finalHelp').textContent='Τελικό σύνολο τυπικών προσόντων και συνέντευξης.';}else if(r.interview.anyEntered){$('interviewSubtotal').textContent=fmt(r.interview.total)+' / 40 (μερικό)';$('interviewResult').textContent=fmt(r.interview.total)+' / 40 (μερικό)';$('finalTotal').textContent='—';$('finalHelp').textContent='Η συνέντευξη δεν έχει συμπληρωθεί πλήρως.';}else{$('interviewSubtotal').textContent='— / 40';$('interviewResult').textContent='— / 40';$('finalTotal').textContent='—';$('finalHelp').textContent='Συμπλήρωσε όλα τα πεδία της συνέντευξης για τελικό /90.'}
 const boxes=[];if(r.unanswered.length)boxes.push('<div class="info"><strong>Χρειάζονται ακόμη στοιχεία:</strong><ul class="edu-list-compact"><li>'+r.unanswered.join('</li><li>')+'</li></ul></div>');if(r.issues.length)boxes.push('<div class="danger"><strong>Έλεγχος προϋποθέσεων:</strong><ul class="edu-list-compact"><li>'+r.issues.join('</li><li>')+'</li></ul></div>');else if(r.eligibleBeforeInterview)boxes.push('<div class="success"><strong>Ο βασικός έλεγχος του 1ου σταδίου είναι θετικός.</strong> Η πρόσκληση σε συνέντευξη εξαρτάται από τη σχετική κατάταξη.</div>');if(r.interviewIssues.length)boxes.push('<div class="danger"><strong>Προφορική εξέταση:</strong><ul class="edu-list-compact"><li>'+r.interviewIssues.join('</li><li>')+'</li></ul></div>');if(r.warnings.length)boxes.push('<div class="warning"><strong>Παρατηρήσεις:</strong><ul class="edu-list-compact"><li>'+r.warnings.join('</li><li>')+'</li></ul></div>');$('eligibilityStatus').innerHTML=boxes.join('');return r}
async function copySummary(){const r=calculate(),p=EuropeanSchools.POSITIONS_2026[v('position')],d=r.service.duration,lines=['Μόρια Απόσπασης σε Ευρωπαϊκά Σχολεία','Θέση: '+(p?p.label:'—'),'Κλάδος: '+(p?(p.librarian?'Δευτεροβάθμια Εκπαίδευση':(p.branches.length===1?normalizeBranchLabel(p.branches[0]):(v('selectedBranch')?normalizeBranchLabel(v('selectedBranch')):p.branches.map(normalizeBranchLabel).join(' / ')))):'—'),'Αναγνωρισμένη υπηρεσία: '+d.years+' έτη, '+d.months+' μήνες, '+d.days+' ημέρες','Α. Κατάρτιση: '+fmt(r.academic.total)+' / 32','Β. Υπηρεσία / εμπειρία: '+fmt(r.service.total)+' / 18','1ο στάδιο Α+Β: '+fmt(r.preInterview)+' / 50','Γ. Συνέντευξη: '+(r.interview.complete?fmt(r.interview.total)+' / 40':'δεν έχει ολοκληρωθεί'),'Τελικό: '+(r.finalTotal===null?'—':fmt(r.finalTotal)+' / 90')];if(r.interview.prerequisiteEntered&&!r.interview.languageBasePassed)lines.push('Σημείωση: δεν επιτεύχθηκε η βάση 5/10 στην προαπαιτούμενη ξένη γλώσσα.');lines.push('','Checklist δικαιολογητικών:',...r.documents.map(d=>'• '+d.text));try{await navigator.clipboard.writeText(lines.join('\n'));$('copyBtn').textContent='Αντιγράφηκε ✓';setTimeout(()=>$('copyBtn').textContent='Αντιγραφή σύνοψης',1400)}catch(e){alert(lines.join('\n'))}}
function reset(){document.querySelectorAll('input[type="checkbox"]').forEach(x=>x.checked=false);document.querySelectorAll('input[type="number"]').forEach(x=>x.value='');document.querySelectorAll('select').forEach(x=>x.selectedIndex=0);['higherEducationSemesters','innovativePrograms','universityTrainingCount','ministryTrainingHours','publicAdminTrainingHours','eapAnnualUnits','eapSemesterUnits'].forEach(id=>$(id).value='0');['hostLanguageLevel','secondWorkingLevel','thirdWorkingLevel','otherEULevel'].forEach(id=>$(id).value='none');calculate();$('position').focus()}
normalizeVisibleBranchLabels();ids.forEach(id=>{const e=$(id);if(e){e.addEventListener('input',calculate);e.addEventListener('change',calculate)}});$('copyBtn').addEventListener('click',copySummary);$('resetBtn').addEventListener('click',reset);calculate();})();
</script>
  <script src="assets/common.js?v=3.20.9-b1"></script>
</body>
</html>
