from pathlib import Path
root=Path(__file__).resolve().parents[1]
g=(root/'ypologismos-morion.php').read_text()
o=(root/'ypologismos-morion-onaseia.php').read_text()
c=(root/'includes/components/asep-pe-academic.php').read_text()
j=(root/'includes/asep-pe-academic.js').read_text()
checks=[]
def ck(name, cond): checks.append((name,bool(cond)))
ck('general requires shared PE academic component', 'asep-pe-academic.php' in g)
ck('Onaseia requires shared PE academic component', 'asep-pe-academic.php' in o)
ck('general renders shared PE academic component', 'renderAsepPeAcademic(' in g)
ck('Onaseia renders shared PE academic component', 'renderAsepPeAcademic(' in o)
ck('general uses AsepPeAcademic.calculate', 'AsepPeAcademic.calculate("asepPeAcademic")' in g)
ck('Onaseia uses AsepPeAcademic.calculate', 'AsepPeAcademic.calculate("asepPeAcademic")' in o)
ck('general has no local syncComputerUI', 'function syncComputerUI' not in g)
ck('Onaseia has no local calculateDetailedAcademic', 'function calculateDetailedAcademic' not in o)
ck('general has no direct EducationAcademic.calculate', 'EducationAcademic.calculate(' not in g)
ck('Onaseia has no direct EducationAcademic.calculate', 'EducationAcademic.calculate(' not in o)
ck('general has no direct AsepLanguageSelector.calculate', 'AsepLanguageSelector.calculate(' not in g)
ck('Onaseia has no direct AsepLanguageSelector.calculate', 'AsepLanguageSelector.calculate(' not in o)
ck('shared component owns language selector', 'renderAsepLanguageSelector(' in c)
ck('shared component owns computer proof', 'renderAsepComputerProof(' in c)
ck('shared component owns training proof', 'renderTrainingProof(' in c)
ck('shared controller owns PE86 UI exclusion', "specialty==='ΠΕ86'" in j or "specialty === 'ΠΕ86'" in j)
ck('shared controller delegates scoring to EducationAcademic', 'EducationAcademic.calculate' in j)
ck('Onaseia still forces TE16 to manual', 'specialty === "ΤΕ16"' in o and 'detailedRadio.disabled = true' in o)
ck('Onaseia still validates manual points', 'OnaseiaAcademic.validateManualAcademicPoints' in o)
ck('Onaseia still keeps manual mode UI', 'name="academicMode" value="manual"' in o)
ck('Onaseia detailed block remains separate from manual wrapper', 'id="detailedAcademic"' in o and 'id="manualAcademic"' in o)
ck('general loads shared controller before inline code', g.index('includes/asep-pe-academic.js') < g.index('<script>\n  let lastResultText'))
ck('Onaseia loads shared controller before inline code', o.index('includes/asep-pe-academic.js') < o.index('<script>\n  let isLiveCalculation'))
ck('shared component is presentation-only re scoring engine', 'Scoring remains exclusively' in c)
passed=sum(v for _,v in checks)
for name,v in checks: print(('✓ ' if v else '✗ ')+name)
print(f'\nPASS: {passed}')
print(f'FAIL: {len(checks)-passed}')
if passed!=len(checks): raise SystemExit(1)
