<?php
/** AUTO-GENERATED school-scoped assignment dataset.
 * Canonical source: includes/teaching-assignments-data.php
 * Regenerate: php tools/scoped-workload-sync.php --write
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
return array (
  0 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Α΄',
    'subject' => 'Στοιχεία Λειτουργικής και Τελετουργικής',
    'section' => 'Μαθήματα Θρησκευτικής Εξειδίκευσης',
    'special_codes' => 
    array (
      0 => 'ΠΕ01',
    ),
    'special_note' => 'Μάθημα εκκλησιαστικής/θρησκευτικής εξειδίκευσης. Εμφανίζεται ως ειδική πρόβλεψη Π.Ε.Σ. και όχι ως βαθμίδα Α΄/Β΄/Γ΄ του γενικού πίνακα αναθέσεων.',
  ),
  1 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Β΄',
    'subject' => 'Θέματα Δογματικής Θεολογίας',
    'section' => 'Μαθήματα Θρησκευτικής Εξειδίκευσης',
    'special_codes' => 
    array (
      0 => 'ΠΕ01',
    ),
    'special_note' => 'Μάθημα εκκλησιαστικής/θρησκευτικής εξειδίκευσης. Εμφανίζεται ως ειδική πρόβλεψη Π.Ε.Σ. και όχι ως βαθμίδα Α΄/Β΄/Γ΄ του γενικού πίνακα αναθέσεων.',
  ),
  2 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Γ΄',
    'subject' => 'Θέματα Χριστιανικής Ηθικής και Ποιμαντικής Θεολογίας',
    'section' => 'Μαθήματα Θρησκευτικής Εξειδίκευσης',
    'special_codes' => 
    array (
      0 => 'ΠΕ01',
    ),
    'special_note' => 'Μάθημα εκκλησιαστικής/θρησκευτικής εξειδίκευσης. Εμφανίζεται ως ειδική πρόβλεψη Π.Ε.Σ. και όχι ως βαθμίδα Α΄/Β΄/Γ΄ του γενικού πίνακα αναθέσεων.',
  ),
  3 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => '',
    'grades' => 
    array (
      0 => 'Α΄',
      1 => 'Β΄',
      2 => 'Γ΄',
    ),
    'section' => 'Μαθήματα Θρησκευτικής Εξειδίκευσης',
    'subject' => 'Βυζαντινή Μουσική',
    'special_codes' => 
    array (
      0 => 'ΠΕ79.01',
      1 => 'ΤΕ16',
    ),
    'special_notes' => 
    array (
      'ΠΕ79.01' => 'Προηγείται του ΤΕ16. Απαιτείται Δίπλωμα Βυζαντινής Μουσικής από αναγνωρισμένο φορέα.',
      'ΤΕ16' => 'Μόνο ελλείψει ΠΕ79.01. Απαιτείται Δίπλωμα Βυζαντινής Μουσικής από αναγνωρισμένο φορέα.',
    ),
    'special_note' => 'Βυζαντινή Μουσική: ΠΕ79.01 και, ελλείψει αυτών, ΤΕ16. Απαραίτητο πρόσθετο προσόν για όλους: Δίπλωμα Βυζαντινής Μουσικής από αναγνωρισμένο φορέα (άρθρο 39 παρ. 9 ν. 3848/2010).',
    'qualification_key' => 'pes_byzantine_music_diploma',
  ),
  4 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => '',
    'grades' => 
    array (
      0 => 'Α΄',
      1 => 'Β΄',
      2 => 'Γ΄',
    ),
    'section' => 'Μαθήματα Θρησκευτικής Εξειδίκευσης',
    'subject' => 'Εικονογραφία',
    'special_codes' => 
    array (
      0 => 'ΠΕ01',
      1 => 'ΠΕ08',
    ),
    'special_note' => 'Εικονογραφία: ανατίθεται μόνο σε εκπαιδευτικούς ΠΕ01/ΠΕ08 που πληρούν τις ειδικές και διαδοχικές προϋποθέσεις της Υ.Α. 71346/Θ2/10-06-2020 (Β΄ 2466), όπως τροποποιήθηκε με την 4404/Θ2/16-01-2023 (Β΄ 253). Η απλή ιδιότητα ΠΕ01 ή ΠΕ08 δεν αρκεί.',
    'qualification_key' => 'pes_iconography_eligibility',
  ),
  5 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Α΄',
    'section' => 'Ελληνική Γλώσσα',
    'subject' => 'Αρχαία Ελληνική Γλώσσα και Γραμματεία',
    'A' => 
    array (
      0 => 'ΠΕ02',
    ),
  ),
  6 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Α΄',
    'section' => 'Ελληνική Γλώσσα',
    'subject' => 'Νέα Ελληνική Γλώσσα και Λογοτεχνία',
    'A' => 
    array (
      0 => 'ΠΕ02',
    ),
  ),
  7 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Α΄',
    'section' => 'Μαθηματικά',
    'subject' => 'Άλγεβρα',
    'A' => 
    array (
      0 => 'ΠΕ03',
    ),
  ),
  8 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Α΄',
    'section' => 'Μαθηματικά',
    'subject' => 'Γεωμετρία',
    'A' => 
    array (
      0 => 'ΠΕ03',
    ),
  ),
  9 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Α΄',
    'section' => 'Φυσικές Επιστήμες',
    'subject' => 'Φυσική',
    'A' => 
    array (
      0 => 'ΠΕ04.01',
    ),
    'B' => 
    array (
      0 => 'ΠΕ04.02',
      1 => 'ΠΕ04.03',
      2 => 'ΠΕ04.04',
      3 => 'ΠΕ04.05',
    ),
  ),
  10 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Α΄',
    'section' => 'Φυσικές Επιστήμες',
    'subject' => 'Χημεία',
    'A' => 
    array (
      0 => 'ΠΕ04.02',
      1 => 'ΠΕ85',
    ),
    'A_notes' => 
    array (
      'ΠΕ85' => 'με πτυχίο Χημικών Μηχανικών',
    ),
    'B' => 
    array (
      0 => 'ΠΕ04.01',
      1 => 'ΠΕ04.03',
      2 => 'ΠΕ04.04',
      3 => 'ΠΕ04.05',
    ),
  ),
  11 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Α΄',
    'section' => 'Φυσικές Επιστήμες',
    'subject' => 'Βιολογία',
    'A' => 
    array (
      0 => 'ΠΕ04.04',
      1 => 'ΠΕ04.03',
    ),
    'B' => 
    array (
      0 => 'ΠΕ04.01',
      1 => 'ΠΕ04.02',
      2 => 'ΠΕ04.05',
      3 => 'ΠΕ87.01',
      4 => 'ΠΕ88.01',
    ),
  ),
  12 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Α΄',
    'section' => '',
    'subject' => 'Ιστορία',
    'A' => 
    array (
      0 => 'ΠΕ02',
      1 => 'ΠΕ33',
    ),
    'B' => 
    array (
      0 => 'ΠΕ05',
      1 => 'ΠΕ06',
      2 => 'ΠΕ07',
      3 => 'ΠΕ78',
    ),
  ),
  13 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Α΄',
    'section' => '',
    'subject' => 'Πολιτική Παιδεία (Οικονομία, Πολιτικοί Θεσμοί και Αρχές Δικαίου και Κοινωνιολογία)',
    'A' => 
    array (
      0 => 'ΠΕ78',
      1 => 'ΠΕ80',
    ),
    'A_notes' => 
    array (
      'ΠΕ80' => 'με προτεραιότητα πρώην ΠΕ09',
    ),
    'B' => 
    array (
      0 => 'ΠΕ02',
    ),
  ),
  14 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Α΄',
    'section' => '',
    'subject' => 'Θρησκευτικά',
    'A' => 
    array (
      0 => 'ΠΕ01',
    ),
  ),
  15 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Α΄',
    'section' => '',
    'subject' => 'Φυσική Αγωγή',
    'A' => 
    array (
      0 => 'ΠΕ11',
    ),
  ),
  16 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Α΄',
    'section' => '',
    'subject' => 'Εφαρμογές Πληροφορικής',
    'A' => 
    array (
      0 => 'ΠΕ86',
    ),
  ),
  17 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Β΄',
    'section' => 'Ελληνική Γλώσσα',
    'subject' => 'Αρχαία Ελληνική Γλώσσα και Γραμματεία',
    'A' => 
    array (
      0 => 'ΠΕ02',
    ),
  ),
  18 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Β΄',
    'section' => 'Ελληνική Γλώσσα',
    'subject' => 'Νέα Ελληνική Γλώσσα και Λογοτεχνία',
    'A' => 
    array (
      0 => 'ΠΕ02',
    ),
  ),
  19 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Β΄',
    'section' => 'Μαθηματικά',
    'subject' => 'Άλγεβρα',
    'A' => 
    array (
      0 => 'ΠΕ03',
    ),
  ),
  20 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Β΄',
    'section' => 'Μαθηματικά',
    'subject' => 'Γεωμετρία',
    'A' => 
    array (
      0 => 'ΠΕ03',
    ),
  ),
  21 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Β΄',
    'section' => 'Φυσικές Επιστήμες',
    'subject' => 'Φυσική',
    'A' => 
    array (
      0 => 'ΠΕ04.01',
    ),
    'B' => 
    array (
      0 => 'ΠΕ04.02',
      1 => 'ΠΕ04.03',
      2 => 'ΠΕ04.04',
      3 => 'ΠΕ04.05',
    ),
  ),
  22 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Β΄',
    'section' => 'Φυσικές Επιστήμες',
    'subject' => 'Χημεία',
    'A' => 
    array (
      0 => 'ΠΕ04.02',
      1 => 'ΠΕ85',
    ),
    'A_notes' => 
    array (
      'ΠΕ85' => 'με πτυχίο Χημικών Μηχανικών',
    ),
    'B' => 
    array (
      0 => 'ΠΕ04.01',
      1 => 'ΠΕ04.03',
      2 => 'ΠΕ04.04',
      3 => 'ΠΕ04.05',
    ),
  ),
  23 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Β΄',
    'section' => 'Φυσικές Επιστήμες',
    'subject' => 'Βιολογία',
    'A' => 
    array (
      0 => 'ΠΕ04.04',
      1 => 'ΠΕ04.03',
    ),
    'B' => 
    array (
      0 => 'ΠΕ04.01',
      1 => 'ΠΕ04.02',
      2 => 'ΠΕ04.05',
      3 => 'ΠΕ87.01',
      4 => 'ΠΕ88.01',
    ),
  ),
  24 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Β΄',
    'section' => '',
    'subject' => 'Εισαγωγή στις Αρχές της Επιστήμης των Η/Υ',
    'A' => 
    array (
      0 => 'ΠΕ86',
    ),
  ),
  25 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Β΄',
    'section' => '',
    'subject' => 'Ιστορία',
    'A' => 
    array (
      0 => 'ΠΕ02',
      1 => 'ΠΕ33',
    ),
    'B' => 
    array (
      0 => 'ΠΕ78',
    ),
  ),
  26 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Β΄',
    'section' => '',
    'subject' => 'Φιλοσοφία',
    'A' => 
    array (
      0 => 'ΠΕ02',
      1 => 'ΠΕ33',
    ),
    'B' => 
    array (
      0 => 'ΠΕ01',
      1 => 'ΠΕ78',
    ),
  ),
  27 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Β΄',
    'section' => '',
    'subject' => 'Θρησκευτικά',
    'A' => 
    array (
      0 => 'ΠΕ01',
    ),
  ),
  28 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Β΄',
    'section' => '',
    'subject' => 'Φυσική Αγωγή',
    'A' => 
    array (
      0 => 'ΠΕ11',
    ),
  ),
  29 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Β΄',
    'section' => 'Ομάδα Προσανατολισμού Ανθρωπιστικών Σπουδών',
    'subject' => 'Αρχαία Ελληνική Γλώσσα και Γραμματεία',
    'A' => 
    array (
      0 => 'ΠΕ02',
    ),
  ),
  30 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Β΄',
    'section' => 'Ομάδα Προσανατολισμού Ανθρωπιστικών Σπουδών',
    'subject' => 'Λατινικά',
    'A' => 
    array (
      0 => 'ΠΕ02',
    ),
  ),
  31 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Β΄',
    'section' => 'Ομάδα Προσανατολισμού Θετικών Σπουδών',
    'subject' => 'Φυσική',
    'A' => 
    array (
      0 => 'ΠΕ04.01',
    ),
    'B' => 
    array (
      0 => 'ΠΕ04.02',
      1 => 'ΠΕ04.03',
      2 => 'ΠΕ04.04',
      3 => 'ΠΕ04.05',
    ),
  ),
  32 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Β΄',
    'section' => 'Ομάδα Προσανατολισμού Θετικών Σπουδών',
    'subject' => 'Μαθηματικά',
    'A' => 
    array (
      0 => 'ΠΕ03',
    ),
  ),
  33 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Γ΄',
    'section' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Θρησκευτικά',
    'A' => 
    array (
      0 => 'ΠΕ01',
    ),
  ),
  34 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Γ΄',
    'section' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Νεοελληνική Γλώσσα και Λογοτεχνία',
    'A' => 
    array (
      0 => 'ΠΕ02',
    ),
  ),
  35 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Γ΄',
    'section' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Ιστορία',
    'A' => 
    array (
      0 => 'ΠΕ02',
      1 => 'ΠΕ33',
    ),
    'B' => 
    array (
      0 => 'ΠΕ78',
    ),
  ),
  36 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Γ΄',
    'section' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Μαθηματικά',
    'A' => 
    array (
      0 => 'ΠΕ03',
    ),
  ),
  37 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Γ΄',
    'section' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Φυσική Αγωγή',
    'A' => 
    array (
      0 => 'ΠΕ11',
    ),
  ),
  38 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Γ΄',
    'section' => 'Ομάδα Προσανατολισμού Ανθρωπιστικών Σπουδών',
    'subject' => 'Αρχαία Ελληνικά',
    'A' => 
    array (
      0 => 'ΠΕ02',
    ),
  ),
  39 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Γ΄',
    'section' => 'Ομάδα Προσανατολισμού Ανθρωπιστικών Σπουδών',
    'subject' => 'Ιστορία',
    'A' => 
    array (
      0 => 'ΠΕ02',
    ),
  ),
  40 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Γ΄',
    'section' => 'Ομάδα Προσανατολισμού Ανθρωπιστικών Σπουδών',
    'subject' => 'Λατινικά',
    'A' => 
    array (
      0 => 'ΠΕ02',
    ),
  ),
  41 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Γ΄',
    'section' => 'Ομάδα Προσανατολισμού Θετικών Σπουδών και Σπουδών Υγείας',
    'subject' => 'Μαθηματικά',
    'A' => 
    array (
      0 => 'ΠΕ03',
    ),
  ),
  42 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Γ΄',
    'section' => 'Ομάδα Προσανατολισμού Θετικών Σπουδών και Σπουδών Υγείας',
    'subject' => 'Βιολογία',
    'A' => 
    array (
      0 => 'ΠΕ04.04',
      1 => 'ΠΕ04.03',
    ),
    'B' => 
    array (
      0 => 'ΠΕ04.01',
      1 => 'ΠΕ04.02',
      2 => 'ΠΕ04.05',
      3 => 'ΠΕ88.01',
    ),
    'C' => 
    array (
      0 => 'ΠΕ87.01',
    ),
  ),
  43 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Γ΄',
    'section' => 'Ομάδα Προσανατολισμού Θετικών Σπουδών και Σπουδών Υγείας',
    'subject' => 'Φυσική',
    'A' => 
    array (
      0 => 'ΠΕ04.01',
    ),
    'B' => 
    array (
      0 => 'ΠΕ04.02',
      1 => 'ΠΕ04.03',
      2 => 'ΠΕ04.04',
      3 => 'ΠΕ04.05',
    ),
  ),
  44 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Γ΄',
    'section' => 'Ομάδα Προσανατολισμού Θετικών Σπουδών και Σπουδών Υγείας',
    'subject' => 'Χημεία',
    'A' => 
    array (
      0 => 'ΠΕ04.02',
      1 => 'ΠΕ85',
    ),
    'A_notes' => 
    array (
      'ΠΕ85' => 'με πτυχίο Χημικών Μηχανικών',
    ),
    'B' => 
    array (
      0 => 'ΠΕ04.01',
      1 => 'ΠΕ04.03',
      2 => 'ΠΕ04.04',
      3 => 'ΠΕ04.05',
    ),
  ),
  45 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Γ΄',
    'section' => 'Ομάδα Προσανατολισμού Σπουδών Οικονομίας και Πληροφορικής',
    'subject' => 'Μαθηματικά',
    'A' => 
    array (
      0 => 'ΠΕ03',
    ),
  ),
  46 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Γ΄',
    'section' => 'Ομάδα Προσανατολισμού Σπουδών Οικονομίας και Πληροφορικής',
    'subject' => 'Οικονομία',
    'A' => 
    array (
      0 => 'ΠΕ80',
    ),
    'A_notes' => 
    array (
      'ΠΕ80' => 'με προτεραιότητα πρώην ΠΕ09',
    ),
    'B' => 
    array (
      0 => 'ΠΕ78',
    ),
  ),
  47 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Γ΄',
    'section' => 'Ομάδα Προσανατολισμού Σπουδών Οικονομίας και Πληροφορικής',
    'subject' => 'Πληροφορική',
    'A' => 
    array (
      0 => 'ΠΕ86',
    ),
  ),
  48 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Α΄',
    'section' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Ξένη Γλώσσα (Αγγλικά ή Γαλλικά ή Γερμανικά)',
    'A' => 
    array (
      0 => 'ΠΕ06',
      1 => 'ΠΕ05',
      2 => 'ΠΕ07',
    ),
    'A_notes' => 
    array (
      'ΠΕ06' => 'για την επιλογή Αγγλικών',
      'ΠΕ05' => 'για την επιλογή Γαλλικών',
      'ΠΕ07' => 'για την επιλογή Γερμανικών',
    ),
    'note' => 'Διδάσκεται μία από τις τρεις γλώσσες που προβλέπει το ωρολόγιο Π.Ε.Σ.',
  ),
  49 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Β΄',
    'section' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Ξένη Γλώσσα (Αγγλικά ή Γαλλικά ή Γερμανικά)',
    'A' => 
    array (
      0 => 'ΠΕ06',
      1 => 'ΠΕ05',
      2 => 'ΠΕ07',
    ),
    'A_notes' => 
    array (
      'ΠΕ06' => 'για την επιλογή Αγγλικών',
      'ΠΕ05' => 'για την επιλογή Γαλλικών',
      'ΠΕ07' => 'για την επιλογή Γερμανικών',
    ),
    'note' => 'Διδάσκεται μία από τις τρεις γλώσσες που προβλέπει το ωρολόγιο Π.Ε.Σ.',
  ),
  50 => 
  array (
    'school' => 'protypo_ekklisiastiko_lykeio',
    'grade' => 'Γ΄',
    'section' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Ξένη Γλώσσα (Αγγλικά ή Γαλλικά ή Γερμανικά)',
    'A' => 
    array (
      0 => 'ΠΕ06',
      1 => 'ΠΕ05',
      2 => 'ΠΕ07',
    ),
    'A_notes' => 
    array (
      'ΠΕ06' => 'για την επιλογή Αγγλικών',
      'ΠΕ05' => 'για την επιλογή Γαλλικών',
      'ΠΕ07' => 'για την επιλογή Γερμανικών',
    ),
    'note' => 'Διδάσκεται μία από τις τρεις γλώσσες που προβλέπει το ωρολόγιο Π.Ε.Σ.',
  ),
);
