<?php
/** AUTO-GENERATED by tools/scoped-workload-sync.php. */
return array (
  'format' => 1,
  'schools' => 
  array (
    0 => 'gymnasio',
    1 => 'gel',
    2 => 'esperino_gymnasio',
    3 => 'esperino_gel',
    4 => 'protypo_ekklisiastiko_gymnasio',
    5 => 'protypo_ekklisiastiko_lykeio',
  ),
  'datasets' => 
  array (
    'assignments' => 
    array (
      'gymnasio' => 
      array (
        'rows' => 23,
        'sha256' => '24d02e0ba5cf7030cb7a9b2d92e1d52ee99d6ed5081a367539dd3f963508cbd1',
      ),
      'gel' => 
      array (
        'rows' => 51,
        'sha256' => '63f364dc2f43ceef7f7a72d391fa128f4c9a48cbd717c9e96c794ba53d6d0347',
      ),
      'esperino_gymnasio' => 
      array (
        'rows' => 17,
        'sha256' => '8f2f5a4f59908da33f7d13014ff7ea256a53e2f8dae52ca5b2b35dec4ccaf8ca',
      ),
      'esperino_gel' => 
      array (
        'rows' => 45,
        'sha256' => '66466052d1d97d306e5db19563738c7453bb630a45c9c67eb653e6d93f89a1aa',
      ),
      'protypo_ekklisiastiko_gymnasio' => 
      array (
        'rows' => 24,
        'sha256' => 'c414fa270742b4083f322a3b24e557752434491eb3e955c744922d1b3815e364',
      ),
      'protypo_ekklisiastiko_lykeio' => 
      array (
        'rows' => 51,
        'sha256' => '7161f0272ed6054a010ceb658eaea5582e6179a23bcb4593a6db01eadebe12ce',
      ),
    ),
    'weekly' => 
    array (
      'gymnasio' => 
      array (
        'rows' => 23,
        'sha256' => 'd5683728b98eb7877532204f3ad9d17072a5655aa46ba670a2ed3f9893b6f32a',
      ),
      'gel' => 
      array (
        'rows' => 32,
        'sha256' => 'd6e2dc193e0d99e9e12c85366ae11011061e4bdceb1c89bff9fec4fbb54e7eff',
      ),
      'esperino_gymnasio' => 
      array (
        'rows' => 17,
        'sha256' => '92bfd44f3e52f4132f06402d87c58ccc7b5e0807700e0a97cab5c40b8a821a81',
      ),
      'esperino_gel' => 
      array (
        'rows' => 29,
        'sha256' => '3d4cb9e4d679ac4db9019573b0041e1ad5a2c25c5cd632fff6ff68c13955c6d3',
      ),
      'protypo_ekklisiastiko_gymnasio' => 
      array (
        'rows' => 24,
        'sha256' => '9857483b3b0216c05d751f54bf588acd6b1c180fb8e450e5758a24a3e6785c63',
      ),
      'protypo_ekklisiastiko_lykeio' => 
      array (
        'rows' => 55,
        'sha256' => '6143b8ff2ff64104e433582a274d0cfcf87ff3e384ec3df8f5c2ea4c56718edb',
      ),
    ),
  ),
);
