<?php
/** AUTO-GENERATED school-scoped weekly timetable dataset.
 * Canonical source: includes/weekly-timetable-data.php
 * Regenerate: php tools/scoped-workload-sync.php --write
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
return array (
  0 => 
  array (
    'course_id' => 'egel.general.archaia',
    'school' => 'esperino_gel',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'section' => 'Ελληνική Γλώσσα',
    'subject' => 'Αρχαία Ελληνική Γλώσσα και Γραμματεία',
    'hours' => 
    array (
      'Α΄' => 2,
      'Β΄' => 1,
    ),
  ),
  1 => 
  array (
    'course_id' => 'egel.general.neoelliniki',
    'school' => 'esperino_gel',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'section' => 'Ελληνική Γλώσσα',
    'subject' => 'Νεοελληνική Γλώσσα και Λογοτεχνία',
    'hours' => 
    array (
      'Α΄' => 4,
      'Β΄' => 4,
      'Γ΄' => 5,
    ),
  ),
  2 => 
  array (
    'course_id' => 'egel.general.algebra',
    'school' => 'esperino_gel',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'section' => 'Μαθηματικά',
    'subject' => 'Άλγεβρα',
    'hours' => 
    array (
      'Α΄' => 2,
      'Β΄' => 3,
    ),
  ),
  3 => 
  array (
    'course_id' => 'egel.general.geometry',
    'school' => 'esperino_gel',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'section' => 'Μαθηματικά',
    'subject' => 'Γεωμετρία',
    'hours' => 
    array (
      'Α΄' => 2,
      'Β΄' => 1,
    ),
  ),
  4 => 
  array (
    'course_id' => 'egel.general.fysiki',
    'school' => 'esperino_gel',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'section' => 'Φυσικές Επιστήμες',
    'subject' => 'Φυσική',
    'hours' => 
    array (
      'Α΄' => 2,
      'Β΄' => 2,
    ),
  ),
  5 => 
  array (
    'course_id' => 'egel.general.ximeia',
    'school' => 'esperino_gel',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'section' => 'Φυσικές Επιστήμες',
    'subject' => 'Χημεία',
    'hours' => 
    array (
      'Α΄' => 2,
      'Β΄' => 1,
    ),
    'hours_display' => 
    array (
      'Β΄' => '1 / 2',
    ),
    'period_hours' => 
    array (
      'Β΄' => 
      array (
        'Α΄ τετράμηνο' => 1,
        'Β΄ τετράμηνο' => 2,
      ),
    ),
    'note_by_grade' => 
    array (
      'Β΄' => '1 ώρα στο Α΄ τετράμηνο και 2 ώρες στο Β΄ τετράμηνο.',
    ),
  ),
  6 => 
  array (
    'course_id' => 'egel.general.viologia',
    'school' => 'esperino_gel',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'section' => 'Φυσικές Επιστήμες',
    'subject' => 'Βιολογία',
    'hours' => 
    array (
      'Α΄' => 2,
      'Β΄' => 2,
    ),
    'hours_display' => 
    array (
      'Β΄' => '2 / 1',
    ),
    'period_hours' => 
    array (
      'Β΄' => 
      array (
        'Α΄ τετράμηνο' => 2,
        'Β΄ τετράμηνο' => 1,
      ),
    ),
    'note_by_grade' => 
    array (
      'Β΄' => '2 ώρες στο Α΄ τετράμηνο και 1 ώρα στο Β΄ τετράμηνο.',
    ),
  ),
  7 => 
  array (
    'course_id' => 'egel.general.thriskeftika',
    'slot_id' => 'egel.general.religion_ethics',
    'school' => 'esperino_gel',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Θρησκευτικά',
    'hours' => 
    array (
      'Α΄' => 1,
      'Β΄' => 1,
      'Γ΄' => 1,
    ),
    'mode' => 'alternative',
  ),
  8 => 
  array (
    'course_id' => 'egel.general.ithiki',
    'slot_id' => 'egel.general.religion_ethics',
    'school' => 'esperino_gel',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Ηθική',
    'hours' => 
    array (
      'Α΄' => 1,
      'Β΄' => 1,
      'Γ΄' => 1,
    ),
    'mode' => 'alternative',
    'condition' => 'Για μαθητές/ήτριες που απαλλάσσονται από το μάθημα των Θρησκευτικών.',
  ),
  9 => 
  array (
    'course_id' => 'egel.general.istoria',
    'slot_id' => 'egel.c.general.orientation_choice',
    'school' => 'esperino_gel',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Ιστορία',
    'hours' => 
    array (
      'Α΄' => 2,
      'Β΄' => 2,
      'Γ΄' => 1,
    ),
    'condition_by_grade' => 
    array (
      'Γ΄' => 'Μόνο για μαθητές/ήτριες των Ομάδων Θετικών Σπουδών & Σπουδών Υγείας ή Σπουδών Οικονομίας & Πληροφορικής.',
    ),
  ),
  10 => 
  array (
    'course_id' => 'egel.general.agglika',
    'school' => 'esperino_gel',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Αγγλικά',
    'hours' => 
    array (
      'Α΄' => 2,
      'Β΄' => 2,
    ),
  ),
  11 => 
  array (
    'course_id' => 'egel.general.fysiki_agogi',
    'school' => 'esperino_gel',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Φυσική Αγωγή',
    'hours' => 
    array (
      'Α΄' => 1,
      'Β΄' => 1,
    ),
  ),
  12 => 
  array (
    'course_id' => 'egel.general.politiki_paideia',
    'school' => 'esperino_gel',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Πολιτική Παιδεία (Οικονομία, Πολιτικοί Θεσμοί και Αρχές Δικαίου και Κοινωνιολογία)',
    'hours' => 
    array (
      'Α΄' => 1,
    ),
  ),
  13 => 
  array (
    'course_id' => 'egel.general.efarmoges_pliroforikis',
    'school' => 'esperino_gel',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Εφαρμογές Πληροφορικής',
    'hours' => 
    array (
      'Α΄' => 2,
    ),
  ),
  14 => 
  array (
    'course_id' => 'egel.general.mathimatika_conditional',
    'slot_id' => 'egel.c.general.orientation_choice',
    'school' => 'esperino_gel',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Μαθηματικά',
    'hours' => 
    array (
      'Γ΄' => 1,
    ),
    'condition' => 'Μόνο για μαθητές/ήτριες που επιλέγουν την Ομάδα Προσανατολισμού Ανθρωπιστικών Σπουδών.',
  ),
  15 => 
  array (
    'course_id' => 'egel.b.humanities.archaia',
    'profile_track' => 'humanities',
    'school' => 'esperino_gel',
    'group' => 'Ομάδα Προσανατολισμού Ανθρωπιστικών Σπουδών',
    'subject' => 'Αρχαία Ελληνική Γλώσσα και Γραμματεία',
    'hours' => 
    array (
      'Β΄' => 3,
    ),
  ),
  16 => 
  array (
    'course_id' => 'egel.b.humanities.latinika',
    'profile_track' => 'humanities',
    'school' => 'esperino_gel',
    'group' => 'Ομάδα Προσανατολισμού Ανθρωπιστικών Σπουδών',
    'subject' => 'Λατινικά',
    'hours' => 
    array (
      'Β΄' => 2,
    ),
  ),
  17 => 
  array (
    'course_id' => 'egel.b.science.fysiki',
    'profile_track' => 'science',
    'school' => 'esperino_gel',
    'group' => 'Ομάδα Προσανατολισμού Θετικών Σπουδών',
    'subject' => 'Φυσική',
    'hours' => 
    array (
      'Β΄' => 2,
    ),
  ),
  18 => 
  array (
    'course_id' => 'egel.b.science.mathimatika',
    'profile_track' => 'science',
    'school' => 'esperino_gel',
    'group' => 'Ομάδα Προσανατολισμού Θετικών Σπουδών',
    'subject' => 'Μαθηματικά',
    'hours' => 
    array (
      'Β΄' => 3,
    ),
  ),
  19 => 
  array (
    'course_id' => 'egel.c.humanities.archaia',
    'profile_track' => 'humanities',
    'school' => 'esperino_gel',
    'group' => 'Ομάδα Προσανατολισμού Ανθρωπιστικών Σπουδών',
    'subject' => 'Αρχαία Ελληνικά',
    'hours' => 
    array (
      'Γ΄' => 6,
    ),
  ),
  20 => 
  array (
    'course_id' => 'egel.c.humanities.istoria',
    'profile_track' => 'humanities',
    'school' => 'esperino_gel',
    'group' => 'Ομάδα Προσανατολισμού Ανθρωπιστικών Σπουδών',
    'subject' => 'Ιστορία',
    'hours' => 
    array (
      'Γ΄' => 6,
    ),
  ),
  21 => 
  array (
    'course_id' => 'egel.c.humanities.latinika',
    'profile_track' => 'humanities',
    'school' => 'esperino_gel',
    'group' => 'Ομάδα Προσανατολισμού Ανθρωπιστικών Σπουδών',
    'subject' => 'Λατινικά',
    'hours' => 
    array (
      'Γ΄' => 6,
    ),
  ),
  22 => 
  array (
    'course_id' => 'egel.c.health.mathimatika',
    'choice_set_id' => 'egel.c.health.field_choice',
    'profile_track' => 'science_health',
    'slot_id' => 'egel.c.health.field_choice',
    'school' => 'esperino_gel',
    'group' => 'Ομάδα Προσανατολισμού Θετικών Σπουδών και Σπουδών Υγείας',
    'subject' => 'Μαθηματικά',
    'hours' => 
    array (
      'Γ΄' => 6,
    ),
    'mode' => 'choice',
    'condition' => 'Για μαθητές/ήτριες που επιλέγουν το 2ο Επιστημονικό Πεδίο.',
  ),
  23 => 
  array (
    'course_id' => 'egel.c.health.viologia',
    'choice_set_id' => 'egel.c.health.field_choice',
    'profile_track' => 'science_health',
    'slot_id' => 'egel.c.health.field_choice',
    'school' => 'esperino_gel',
    'group' => 'Ομάδα Προσανατολισμού Θετικών Σπουδών και Σπουδών Υγείας',
    'subject' => 'Βιολογία',
    'hours' => 
    array (
      'Γ΄' => 6,
    ),
    'mode' => 'choice',
    'condition' => 'Για μαθητές/ήτριες που επιλέγουν το 3ο Επιστημονικό Πεδίο.',
  ),
  24 => 
  array (
    'course_id' => 'egel.c.health.fysiki',
    'profile_track' => 'science_health',
    'school' => 'esperino_gel',
    'group' => 'Ομάδα Προσανατολισμού Θετικών Σπουδών και Σπουδών Υγείας',
    'subject' => 'Φυσική',
    'hours' => 
    array (
      'Γ΄' => 6,
    ),
  ),
  25 => 
  array (
    'course_id' => 'egel.c.health.ximeia',
    'profile_track' => 'science_health',
    'school' => 'esperino_gel',
    'group' => 'Ομάδα Προσανατολισμού Θετικών Σπουδών και Σπουδών Υγείας',
    'subject' => 'Χημεία',
    'hours' => 
    array (
      'Γ΄' => 6,
    ),
  ),
  26 => 
  array (
    'course_id' => 'egel.c.econ.mathimatika',
    'profile_track' => 'economics_it',
    'school' => 'esperino_gel',
    'group' => 'Ομάδα Προσανατολισμού Σπουδών Οικονομίας και Πληροφορικής',
    'subject' => 'Μαθηματικά',
    'hours' => 
    array (
      'Γ΄' => 6,
    ),
  ),
  27 => 
  array (
    'course_id' => 'egel.c.econ.pliroforiki',
    'profile_track' => 'economics_it',
    'school' => 'esperino_gel',
    'group' => 'Ομάδα Προσανατολισμού Σπουδών Οικονομίας και Πληροφορικής',
    'subject' => 'Πληροφορική',
    'hours' => 
    array (
      'Γ΄' => 6,
    ),
  ),
  28 => 
  array (
    'course_id' => 'egel.c.econ.oikonomia',
    'profile_track' => 'economics_it',
    'school' => 'esperino_gel',
    'group' => 'Ομάδα Προσανατολισμού Σπουδών Οικονομίας και Πληροφορικής',
    'subject' => 'Οικονομία',
    'hours' => 
    array (
      'Γ΄' => 6,
    ),
  ),
);
