<?php
/** AUTO-GENERATED school-scoped weekly timetable dataset.
 * Canonical source: includes/weekly-timetable-data.php
 * Regenerate: php tools/scoped-workload-sync.php --write
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
return array (
  0 => 
  array (
    'course_id' => 'pes.lykeio.a.archaia',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Αρχαία Ελληνική Γλώσσα και Γραμματεία',
    'hours' => 
    array (
      'Α΄' => 4,
    ),
  ),
  1 => 
  array (
    'course_id' => 'pes.lykeio.a.neoelliniki',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Νέα Ελληνική Γλώσσα και Λογοτεχνία',
    'hours' => 
    array (
      'Α΄' => 4,
    ),
  ),
  2 => 
  array (
    'course_id' => 'pes.lykeio.a.thriskeftika',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Θρησκευτικά',
    'hours' => 
    array (
      'Α΄' => 2,
    ),
  ),
  3 => 
  array (
    'course_id' => 'pes.lykeio.a.istoria',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Ιστορία',
    'hours' => 
    array (
      'Α΄' => 2,
    ),
  ),
  4 => 
  array (
    'course_id' => 'pes.lykeio.a.algebra',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Άλγεβρα',
    'hours' => 
    array (
      'Α΄' => 3,
    ),
  ),
  5 => 
  array (
    'course_id' => 'pes.lykeio.a.geometria',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Γεωμετρία',
    'hours' => 
    array (
      'Α΄' => 1,
    ),
  ),
  6 => 
  array (
    'course_id' => 'pes.lykeio.a.xeni_glossa',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Ξένη Γλώσσα (Αγγλικά ή Γαλλικά ή Γερμανικά)',
    'hours' => 
    array (
      'Α΄' => 2,
    ),
    'mode' => 'choice',
    'assignment_link_status' => 'choice_dependent',
    'assignment_choice_options' => 
    array (
      0 => 
      array (
        'label' => 'Αγγλικά',
        'subject' => 'Ξένη Γλώσσα (Αγγλικά ή Γαλλικά ή Γερμανικά)',
        'codes' => 
        array (
          0 => 'ΠΕ06',
        ),
      ),
      1 => 
      array (
        'label' => 'Γαλλικά',
        'subject' => 'Ξένη Γλώσσα (Αγγλικά ή Γαλλικά ή Γερμανικά)',
        'codes' => 
        array (
          0 => 'ΠΕ05',
        ),
      ),
      2 => 
      array (
        'label' => 'Γερμανικά',
        'subject' => 'Ξένη Γλώσσα (Αγγλικά ή Γαλλικά ή Γερμανικά)',
        'codes' => 
        array (
          0 => 'ΠΕ07',
        ),
      ),
    ),
  ),
  7 => 
  array (
    'course_id' => 'pes.lykeio.a.fysiki',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Φυσική',
    'hours' => 
    array (
      'Α΄' => 2,
    ),
  ),
  8 => 
  array (
    'course_id' => 'pes.lykeio.a.chimeia',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Χημεία',
    'hours' => 
    array (
      'Α΄' => 2,
    ),
  ),
  9 => 
  array (
    'course_id' => 'pes.lykeio.a.biologia',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Βιολογία',
    'hours' => 
    array (
      'Α΄' => 2,
    ),
  ),
  10 => 
  array (
    'course_id' => 'pes.lykeio.a.fysiki_agogi',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Φυσική Αγωγή',
    'hours' => 
    array (
      'Α΄' => 2,
    ),
  ),
  11 => 
  array (
    'course_id' => 'pes.lykeio.a.politiki_paideia',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Πολιτική Παιδεία (Οικονομία, Πολιτικοί Θεσμοί και Αρχές Δικαίου και Κοινωνιολογία)',
    'hours' => 
    array (
      'Α΄' => 2,
    ),
  ),
  12 => 
  array (
    'course_id' => 'pes.lykeio.a.efarmoges_pliroforikis',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Εφαρμογές Πληροφορικής',
    'hours' => 
    array (
      'Α΄' => 1,
    ),
  ),
  13 => 
  array (
    'course_id' => 'pes.lykeio.a.leitourgiki_teletourgiki',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Θρησκευτικής Εξειδίκευσης',
    'subject' => 'Στοιχεία Λειτουργικής και Τελετουργικής',
    'hours' => 
    array (
      'Α΄' => 2,
    ),
  ),
  14 => 
  array (
    'course_id' => 'pes.lykeio.a.vyzantini_mousiki',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Θρησκευτικής Εξειδίκευσης',
    'subject' => 'Βυζαντινή Μουσική',
    'hours' => 
    array (
      'Α΄' => 2,
    ),
  ),
  15 => 
  array (
    'course_id' => 'pes.lykeio.a.eikonografia',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Θρησκευτικής Εξειδίκευσης',
    'subject' => 'Εικονογραφία',
    'hours' => 
    array (
      'Α΄' => 2,
    ),
  ),
  16 => 
  array (
    'course_id' => 'pes.lykeio.b.archaia',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Αρχαία Ελληνική Γλώσσα και Γραμματεία',
    'hours' => 
    array (
      'Β΄' => 2,
    ),
  ),
  17 => 
  array (
    'course_id' => 'pes.lykeio.b.neoelliniki',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Νέα Ελληνική Γλώσσα και Λογοτεχνία',
    'hours' => 
    array (
      'Β΄' => 4,
    ),
  ),
  18 => 
  array (
    'course_id' => 'pes.lykeio.b.algebra',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Άλγεβρα',
    'hours' => 
    array (
      'Β΄' => 3,
    ),
  ),
  19 => 
  array (
    'course_id' => 'pes.lykeio.b.geometria',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Γεωμετρία',
    'hours' => 
    array (
      'Β΄' => 1,
    ),
  ),
  20 => 
  array (
    'course_id' => 'pes.lykeio.b.fysiki',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Φυσική',
    'hours' => 
    array (
      'Β΄' => 2,
    ),
  ),
  21 => 
  array (
    'course_id' => 'pes.lykeio.b.chimeia',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Χημεία',
    'hours' => 
    array (
      'Β΄' => 1,
    ),
  ),
  22 => 
  array (
    'course_id' => 'pes.lykeio.b.biologia',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Βιολογία',
    'hours' => 
    array (
      'Β΄' => 2,
    ),
  ),
  23 => 
  array (
    'course_id' => 'pes.lykeio.b.arxes_ypologiston',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Εισαγωγή στις Αρχές της Επιστήμης των Η/Υ',
    'hours' => 
    array (
      'Β΄' => 2,
    ),
  ),
  24 => 
  array (
    'course_id' => 'pes.lykeio.b.istoria',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Ιστορία',
    'hours' => 
    array (
      'Β΄' => 2,
    ),
  ),
  25 => 
  array (
    'course_id' => 'pes.lykeio.b.filosofia',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Φιλοσοφία',
    'hours' => 
    array (
      'Β΄' => 1,
    ),
  ),
  26 => 
  array (
    'course_id' => 'pes.lykeio.b.thriskeftika',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Θρησκευτικά',
    'hours' => 
    array (
      'Β΄' => 2,
    ),
  ),
  27 => 
  array (
    'course_id' => 'pes.lykeio.b.xeni_glossa',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Ξένη Γλώσσα (Αγγλικά ή Γαλλικά ή Γερμανικά)',
    'hours' => 
    array (
      'Β΄' => 1,
    ),
    'mode' => 'choice',
    'assignment_link_status' => 'choice_dependent',
    'assignment_choice_options' => 
    array (
      0 => 
      array (
        'label' => 'Αγγλικά',
        'subject' => 'Ξένη Γλώσσα (Αγγλικά ή Γαλλικά ή Γερμανικά)',
        'codes' => 
        array (
          0 => 'ΠΕ06',
        ),
      ),
      1 => 
      array (
        'label' => 'Γαλλικά',
        'subject' => 'Ξένη Γλώσσα (Αγγλικά ή Γαλλικά ή Γερμανικά)',
        'codes' => 
        array (
          0 => 'ΠΕ05',
        ),
      ),
      2 => 
      array (
        'label' => 'Γερμανικά',
        'subject' => 'Ξένη Γλώσσα (Αγγλικά ή Γαλλικά ή Γερμανικά)',
        'codes' => 
        array (
          0 => 'ΠΕ07',
        ),
      ),
    ),
  ),
  28 => 
  array (
    'course_id' => 'pes.lykeio.b.fysiki_agogi',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Φυσική Αγωγή',
    'hours' => 
    array (
      'Β΄' => 1,
    ),
  ),
  29 => 
  array (
    'course_id' => 'pes.lykeio.b.dogmatiki',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Θρησκευτικής Εξειδίκευσης',
    'subject' => 'Θέματα Δογματικής Θεολογίας',
    'hours' => 
    array (
      'Β΄' => 2,
    ),
  ),
  30 => 
  array (
    'course_id' => 'pes.lykeio.b.vyzantini_mousiki',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Θρησκευτικής Εξειδίκευσης',
    'subject' => 'Βυζαντινή Μουσική',
    'hours' => 
    array (
      'Β΄' => 2,
    ),
  ),
  31 => 
  array (
    'course_id' => 'pes.lykeio.b.eikonografia',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Θρησκευτικής Εξειδίκευσης',
    'subject' => 'Εικονογραφία',
    'hours' => 
    array (
      'Β΄' => 2,
    ),
  ),
  32 => 
  array (
    'course_id' => 'pes.lykeio.b.hum.archaia',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Ομάδα Προσανατολισμού Ανθρωπιστικών Σπουδών',
    'subject' => 'Αρχαία Ελληνική Γλώσσα και Γραμματεία',
    'hours' => 
    array (
      'Β΄' => 3,
    ),
  ),
  33 => 
  array (
    'course_id' => 'pes.lykeio.b.hum.latinika',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Ομάδα Προσανατολισμού Ανθρωπιστικών Σπουδών',
    'subject' => 'Λατινικά',
    'hours' => 
    array (
      'Β΄' => 2,
    ),
  ),
  34 => 
  array (
    'course_id' => 'pes.lykeio.b.sci.fysiki',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Ομάδα Προσανατολισμού Θετικών Σπουδών',
    'subject' => 'Φυσική',
    'hours' => 
    array (
      'Β΄' => 3,
    ),
  ),
  35 => 
  array (
    'course_id' => 'pes.lykeio.b.sci.mathimatika',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Ομάδα Προσανατολισμού Θετικών Σπουδών',
    'subject' => 'Μαθηματικά',
    'hours' => 
    array (
      'Β΄' => 2,
    ),
  ),
  36 => 
  array (
    'course_id' => 'pes.lykeio.g.thriskeftika',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Θρησκευτικά',
    'hours' => 
    array (
      'Γ΄' => 1,
    ),
  ),
  37 => 
  array (
    'course_id' => 'pes.lykeio.g.neoelliniki',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Νεοελληνική Γλώσσα και Λογοτεχνία',
    'hours' => 
    array (
      'Γ΄' => 6,
    ),
    'note' => '5 ώρες διδασκαλία + 1 ώρα για ανακεφαλαίωση/ερωτήσεις, σύμφωνα με το ωρολόγιο.',
  ),
  38 => 
  array (
    'course_id' => 'pes.lykeio.g.mathimatika_gen',
    'slot_id' => 'pes.lykeio.g.general.choice',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Μαθηματικά',
    'hours' => 
    array (
      'Γ΄' => 2,
    ),
    'mode' => 'alternative',
    'condition' => 'Για τους/τις μαθητές/ήτριες της Ομάδας Προσανατολισμού Ανθρωπιστικών Σπουδών.',
  ),
  39 => 
  array (
    'course_id' => 'pes.lykeio.g.istoria_gen',
    'slot_id' => 'pes.lykeio.g.general.choice',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Ιστορία',
    'hours' => 
    array (
      'Γ΄' => 2,
    ),
    'mode' => 'alternative',
    'condition' => 'Για τους/τις μαθητές/ήτριες των Ομάδων Προσανατολισμού Θετικών Σπουδών και Σπουδών Υγείας ή Σπουδών Οικονομίας και Πληροφορικής.',
  ),
  40 => 
  array (
    'course_id' => 'pes.lykeio.g.xeni_glossa',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Ξένη Γλώσσα (Αγγλικά ή Γαλλικά ή Γερμανικά)',
    'hours' => 
    array (
      'Γ΄' => 1,
    ),
    'mode' => 'choice',
    'assignment_link_status' => 'choice_dependent',
    'assignment_choice_options' => 
    array (
      0 => 
      array (
        'label' => 'Αγγλικά',
        'subject' => 'Ξένη Γλώσσα (Αγγλικά ή Γαλλικά ή Γερμανικά)',
        'codes' => 
        array (
          0 => 'ΠΕ06',
        ),
      ),
      1 => 
      array (
        'label' => 'Γαλλικά',
        'subject' => 'Ξένη Γλώσσα (Αγγλικά ή Γαλλικά ή Γερμανικά)',
        'codes' => 
        array (
          0 => 'ΠΕ05',
        ),
      ),
      2 => 
      array (
        'label' => 'Γερμανικά',
        'subject' => 'Ξένη Γλώσσα (Αγγλικά ή Γαλλικά ή Γερμανικά)',
        'codes' => 
        array (
          0 => 'ΠΕ07',
        ),
      ),
    ),
  ),
  41 => 
  array (
    'course_id' => 'pes.lykeio.g.fysiki_agogi',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Γενικής Παιδείας',
    'subject' => 'Φυσική Αγωγή',
    'hours' => 
    array (
      'Γ΄' => 1,
    ),
  ),
  42 => 
  array (
    'course_id' => 'pes.lykeio.g.ithiki_poimantiki',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Θρησκευτικής Εξειδίκευσης',
    'subject' => 'Θέματα Χριστιανικής Ηθικής και Ποιμαντικής Θεολογίας',
    'hours' => 
    array (
      'Γ΄' => 2,
    ),
  ),
  43 => 
  array (
    'course_id' => 'pes.lykeio.g.vyzantini_mousiki',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Θρησκευτικής Εξειδίκευσης',
    'subject' => 'Βυζαντινή Μουσική',
    'hours' => 
    array (
      'Γ΄' => 2,
    ),
  ),
  44 => 
  array (
    'course_id' => 'pes.lykeio.g.eikonografia',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Μαθήματα Θρησκευτικής Εξειδίκευσης',
    'subject' => 'Εικονογραφία',
    'hours' => 
    array (
      'Γ΄' => 2,
    ),
  ),
  45 => 
  array (
    'course_id' => 'pes.lykeio.g.hum.archaia',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Ομάδα Προσανατολισμού Ανθρωπιστικών Σπουδών',
    'subject' => 'Αρχαία Ελληνικά',
    'hours' => 
    array (
      'Γ΄' => 6,
    ),
  ),
  46 => 
  array (
    'course_id' => 'pes.lykeio.g.hum.istoria',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Ομάδα Προσανατολισμού Ανθρωπιστικών Σπουδών',
    'subject' => 'Ιστορία',
    'hours' => 
    array (
      'Γ΄' => 6,
    ),
  ),
  47 => 
  array (
    'course_id' => 'pes.lykeio.g.hum.latinika',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Ομάδα Προσανατολισμού Ανθρωπιστικών Σπουδών',
    'subject' => 'Λατινικά',
    'hours' => 
    array (
      'Γ΄' => 6,
    ),
  ),
  48 => 
  array (
    'course_id' => 'pes.lykeio.g.sci.mathimatika',
    'slot_id' => 'pes.lykeio.g.science_field_choice',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Ομάδα Προσανατολισμού Θετικών Σπουδών και Σπουδών Υγείας',
    'subject' => 'Μαθηματικά',
    'hours' => 
    array (
      'Γ΄' => 6,
    ),
    'mode' => 'alternative',
    'condition' => 'Για το 2ο Επιστημονικό Πεδίο.',
  ),
  49 => 
  array (
    'course_id' => 'pes.lykeio.g.sci.biologia',
    'slot_id' => 'pes.lykeio.g.science_field_choice',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Ομάδα Προσανατολισμού Θετικών Σπουδών και Σπουδών Υγείας',
    'subject' => 'Βιολογία',
    'hours' => 
    array (
      'Γ΄' => 6,
    ),
    'mode' => 'alternative',
    'condition' => 'Για το 3ο Επιστημονικό Πεδίο.',
  ),
  50 => 
  array (
    'course_id' => 'pes.lykeio.g.sci.fysiki',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Ομάδα Προσανατολισμού Θετικών Σπουδών και Σπουδών Υγείας',
    'subject' => 'Φυσική',
    'hours' => 
    array (
      'Γ΄' => 6,
    ),
  ),
  51 => 
  array (
    'course_id' => 'pes.lykeio.g.sci.chimeia',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Ομάδα Προσανατολισμού Θετικών Σπουδών και Σπουδών Υγείας',
    'subject' => 'Χημεία',
    'hours' => 
    array (
      'Γ΄' => 6,
    ),
  ),
  52 => 
  array (
    'course_id' => 'pes.lykeio.g.econ.mathimatika',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Ομάδα Προσανατολισμού Σπουδών Οικονομίας και Πληροφορικής',
    'subject' => 'Μαθηματικά',
    'hours' => 
    array (
      'Γ΄' => 6,
    ),
  ),
  53 => 
  array (
    'course_id' => 'pes.lykeio.g.econ.pliroforiki',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Ομάδα Προσανατολισμού Σπουδών Οικονομίας και Πληροφορικής',
    'subject' => 'Πληροφορική',
    'hours' => 
    array (
      'Γ΄' => 6,
    ),
  ),
  54 => 
  array (
    'course_id' => 'pes.lykeio.g.econ.oikonomia',
    'school' => 'protypo_ekklisiastiko_lykeio',
    'group' => 'Ομάδα Προσανατολισμού Σπουδών Οικονομίας και Πληροφορικής',
    'subject' => 'Οικονομία',
    'hours' => 
    array (
      'Γ΄' => 6,
    ),
  ),
);
