<?php
/** AUTO-GENERATED school-scoped weekly timetable dataset.
 * Canonical source: includes/weekly-timetable-data.php
 * Regenerate: php tools/scoped-workload-sync.php --write
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
return array (
  0 => 
  array (
    'course_id' => 'pes.gym.glossiki',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Κοινό πρόγραμμα',
    'subject' => 'Γλωσσική Διδασκαλία',
    'hours' => 
    array (
      'Α΄' => 3,
      'Β΄' => 2,
      'Γ΄' => 2,
    ),
  ),
  1 => 
  array (
    'course_id' => 'pes.gym.logotexnia',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Κοινό πρόγραμμα',
    'subject' => 'Νεοελληνική Λογοτεχνία',
    'hours' => 
    array (
      'Α΄' => 2,
      'Β΄' => 2,
      'Γ΄' => 2,
    ),
  ),
  2 => 
  array (
    'course_id' => 'pes.gym.archaia_glossa',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Κοινό πρόγραμμα',
    'subject' => 'Αρχαία Ελληνική Γλώσσα',
    'hours' => 
    array (
      'Α΄' => 2,
      'Β΄' => 2,
      'Γ΄' => 2,
    ),
  ),
  3 => 
  array (
    'course_id' => 'pes.gym.archaia_metafrasi',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Κοινό πρόγραμμα',
    'subject' => 'Αρχαία Ελληνικά Κείμενα από μετάφραση',
    'hours' => 
    array (
      'Α΄' => 2,
      'Β΄' => 2,
      'Γ΄' => 2,
    ),
  ),
  4 => 
  array (
    'course_id' => 'pes.gym.mathimatika',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Κοινό πρόγραμμα',
    'subject' => 'Μαθηματικά',
    'hours' => 
    array (
      'Α΄' => 4,
      'Β΄' => 4,
      'Γ΄' => 4,
    ),
  ),
  5 => 
  array (
    'course_id' => 'pes.gym.fysiki',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Κοινό πρόγραμμα',
    'subject' => 'Φυσική',
    'hours' => 
    array (
      'Α΄' => 1,
      'Β΄' => 2,
      'Γ΄' => 2,
    ),
  ),
  6 => 
  array (
    'course_id' => 'pes.gym.chimeia',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Κοινό πρόγραμμα',
    'subject' => 'Χημεία',
    'hours' => 
    array (
      'Β΄' => 1,
      'Γ΄' => 1,
    ),
  ),
  7 => 
  array (
    'course_id' => 'pes.gym.biologia',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Κοινό πρόγραμμα',
    'subject' => 'Βιολογία',
    'hours' => 
    array (
      'Α΄' => 1,
      'Β΄' => 1,
      'Γ΄' => 1,
    ),
  ),
  8 => 
  array (
    'course_id' => 'pes.gym.geologia_geografia',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Κοινό πρόγραμμα',
    'subject' => 'Γεωλογία - Γεωγραφία',
    'hours' => 
    array (
      'Α΄' => 1,
      'Β΄' => 2,
    ),
  ),
  9 => 
  array (
    'course_id' => 'pes.gym.oikiaki_oikonomia',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Κοινό πρόγραμμα',
    'subject' => 'Οικιακή Οικονομία',
    'hours' => 
    array (
      'Α΄' => 1,
    ),
  ),
  10 => 
  array (
    'course_id' => 'pes.gym.istoria',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Κοινό πρόγραμμα',
    'subject' => 'Ιστορία',
    'hours' => 
    array (
      'Α΄' => 2,
      'Β΄' => 2,
      'Γ΄' => 2,
    ),
  ),
  11 => 
  array (
    'course_id' => 'pes.gym.koinoniki_politiki',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Κοινό πρόγραμμα',
    'subject' => 'Κοινωνική και Πολιτική Αγωγή',
    'hours' => 
    array (
      'Γ΄' => 1,
    ),
  ),
  12 => 
  array (
    'course_id' => 'pes.gym.oikonomika',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Κοινό πρόγραμμα',
    'subject' => 'Οικονομικά',
    'hours' => 
    array (
      'Γ΄' => 1,
    ),
  ),
  13 => 
  array (
    'course_id' => 'pes.gym.thriskeftika',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Κοινό πρόγραμμα',
    'subject' => 'Θρησκευτικά',
    'hours' => 
    array (
      'Α΄' => 2,
      'Β΄' => 2,
      'Γ΄' => 2,
    ),
  ),
  14 => 
  array (
    'course_id' => 'pes.gym.agglika',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Κοινό πρόγραμμα',
    'subject' => 'Αγγλικά',
    'hours' => 
    array (
      'Α΄' => 2,
      'Β΄' => 2,
      'Γ΄' => 2,
    ),
  ),
  15 => 
  array (
    'course_id' => 'pes.gym.deuteri_xeni',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Κοινό πρόγραμμα',
    'subject' => 'Γαλλικά / Γερμανικά / Ρωσικά / Αραβικά / Τουρκικά',
    'hours' => 
    array (
      'Α΄' => 2,
      'Β΄' => 2,
      'Γ΄' => 2,
    ),
    'mode' => 'choice',
    'condition' => 'Μία από τις προβλεπόμενες ξένες γλώσσες.',
    'assignment_link_status' => 'regulatory_gap',
    'assignment_link_note' => 'Οι Γαλλικές/Γερμανικές αντιστοιχούν σε ΠΕ05/ΠΕ07. Για Ρωσικά, Αραβικά και Τουρκικά δεν αποδίδεται κλάδος χωρίς ρητή ισχύουσα διάταξη ανάθεσης.',
    'assignment_gap_confirmed' => true,
    'assignment_gap_kind' => 'partial_language_assignment_gap',
    'assignment_gap_timetable_source' => 'ΦΕΚ Β΄ 4438/2021, όπως ισχύει με ΦΕΚ Β΄ 4881/2025',
    'assignment_gap_assignment_source' => 'ΦΕΚ Β΄ 2583/2026, όπως τροποποιήθηκε με Β΄ 5555/2026 + ισχύουσες οδηγίες στελέχωσης Π.Ε.Σ. 2026-2027',
    'assignment_gap_inference_guard' => 'no_unpublished_language_specialty_inference',
    'assignment_gap_related_scope' => 'Ρωσικά / Αραβικά / Τουρκικά· Γαλλικά/Γερμανικά παραμένουν ΠΕ05/ΠΕ07 στο εργαλείο αναθέσεων',
  ),
  16 => 
  array (
    'course_id' => 'pes.gym.fysiki_agogi',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Κοινό πρόγραμμα',
    'subject' => 'Φυσική Αγωγή',
    'hours' => 
    array (
      'Α΄' => 2,
      'Β΄' => 2,
      'Γ΄' => 2,
    ),
  ),
  17 => 
  array (
    'course_id' => 'pes.gym.pliroforiki',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Κοινό πρόγραμμα',
    'subject' => 'Πληροφορική',
    'hours' => 
    array (
      'Α΄' => 2,
      'Β΄' => 1,
      'Γ΄' => 1,
    ),
  ),
  18 => 
  array (
    'course_id' => 'pes.gym.ergastiria_deksiotiton',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Κοινό πρόγραμμα',
    'subject' => 'Εργαστήρια Δεξιοτήτων',
    'hours' => 
    array (
      'Α΄' => 1,
      'Β΄' => 1,
      'Γ΄' => 1,
    ),
  ),
  19 => 
  array (
    'course_id' => 'pes.gym.agia_grafi',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Μαθήματα Θρησκευτικής Εξειδίκευσης',
    'subject' => 'Θέματα από την Αγία Γραφή',
    'hours' => 
    array (
      'Α΄' => 2,
    ),
  ),
  20 => 
  array (
    'course_id' => 'pes.gym.leitourgiki_zoi',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Μαθήματα Θρησκευτικής Εξειδίκευσης',
    'subject' => 'Λειτουργική Ζωή της Εκκλησίας',
    'hours' => 
    array (
      'Β΄' => 2,
    ),
  ),
  21 => 
  array (
    'course_id' => 'pes.gym.ekklisiastiki_istoria_pateres',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Μαθήματα Θρησκευτικής Εξειδίκευσης',
    'subject' => 'Εκκλησιαστική Ιστορία και Πατέρες και Θεολόγοι της Εκκλησίας',
    'hours' => 
    array (
      'Γ΄' => 2,
    ),
  ),
  22 => 
  array (
    'course_id' => 'pes.gym.vyzantini_mousiki',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Μαθήματα Θρησκευτικής Εξειδίκευσης',
    'subject' => 'Βυζαντινή Μουσική',
    'hours' => 
    array (
      'Α΄' => 2,
      'Β΄' => 2,
      'Γ΄' => 2,
    ),
  ),
  23 => 
  array (
    'course_id' => 'pes.gym.eikonografia',
    'school' => 'protypo_ekklisiastiko_gymnasio',
    'group' => 'Μαθήματα Θρησκευτικής Εξειδίκευσης',
    'subject' => 'Εικονογραφία',
    'hours' => 
    array (
      'Α΄' => 2,
      'Β΄' => 2,
      'Γ΄' => 2,
    ),
  ),
);
