<?php
/**
 * Generate / verify the small school-scoped regulatory datasets used by
 * ypologismos-didaktikon-anagkon.php.
 *
 * Usage:
 *   php tools/scoped-workload-sync.php --check   # default, exits 1 on mismatch
 *   php tools/scoped-workload-sync.php --write   # regenerate snapshots, then verify
 *
 * Run --write after every change to canonical assignments or weekly timetable
 * data. This keeps the fast staffing-simulator datasets bit-for-bit equivalent
 * to the public "Αναθέσεις" and "Ωρολόγιο" regulatory datasets.
 */

if (PHP_SAPI !== 'cli') {
    if (!headers_sent()) {
        header('HTTP/1.1 403 Forbidden');
        header('Content-Type: text/plain; charset=UTF-8');
    }
    echo "CLI only.\n";
    exit;
}

$root = dirname(__DIR__);
$includes = $root . '/includes';
require_once $includes . '/scoped-workload-config.php';
require_once $includes . '/teaching-assignments-data.php';
require_once $includes . '/weekly-timetable-data.php';

$mode = in_array('--write', $argv, true) ? 'write' : 'check';
$schools = scopedWorkloadAllSnapshotSchools();

function scopedSyncFilterRows($rows, $school)
{
    $result = array();
    foreach ($rows as $row) {
        if (isset($row['school']) && (string) $row['school'] === (string) $school) {
            $result[] = $row;
        }
    }
    return $result;
}

function scopedSyncPhpFile($dataset, $school, $rows)
{
    $label = $dataset === 'assignments' ? 'assignment' : 'weekly timetable';
    return "<?php\n"
        . "/** AUTO-GENERATED school-scoped " . $label . " dataset.\n"
        . " * Canonical source: includes/" . ($dataset === 'assignments' ? 'teaching-assignments-data.php' : 'weekly-timetable-data.php') . "\n"
        . " * Regenerate: php tools/scoped-workload-sync.php --write\n"
        . " * DO NOT EDIT THIS FILE DIRECTLY.\n"
        . " */\n"
        . "return " . var_export($rows, true) . ";\n";
}

function scopedSyncHash($rows)
{
    return hash('sha256', serialize($rows));
}

$canonical = array(
    'assignments' => teachingAssignmentsData(),
    'weekly' => weeklyTimetableRows(),
);

$prefix = array(
    'assignments' => 'assignments-',
    'weekly' => 'weekly-',
);

$ok = true;
$summary = array();
foreach (array('assignments', 'weekly') as $dataset) {
    foreach ($schools as $school) {
        $expected = scopedSyncFilterRows($canonical[$dataset], $school);
        $path = $includes . '/scoped-workload/' . $prefix[$dataset] . $school . '.php';

        if ($mode === 'write') {
            $bytes = file_put_contents($path, scopedSyncPhpFile($dataset, $school, $expected));
            if ($bytes === false) {
                fwrite(STDERR, "WRITE FAIL: " . $path . "\n");
                $ok = false;
                continue;
            }
            // Ensure the runtime mtime safety net sees the newly generated file
            // as at least as new as the canonical source on coarse filesystems.
            @touch($path, time() + 1);
            clearstatcache(true, $path);
        }

        if (!is_file($path)) {
            echo "MISSING  " . $dataset . "  " . $school . "\n";
            $ok = false;
            continue;
        }

        $actual = require $path;
        if (!is_array($actual)) {
            echo "INVALID  " . $dataset . "  " . $school . "\n";
            $ok = false;
            continue;
        }

        $same = ($actual === $expected);
        $status = $same ? 'OK' : 'STALE';
        printf(
            "%-5s  %-11s  %-38s rows=%4d  sha256=%s\n",
            $status,
            $dataset,
            $school,
            count($expected),
            substr(scopedSyncHash($expected), 0, 16)
        );
        if (!$same) {
            $ok = false;
        }
        $summary[] = array($dataset, $school, count($expected), scopedSyncHash($expected));
    }
}

$manifestPath = $includes . '/scoped-workload/manifest.php';
if ($mode === 'write') {
    $manifest = array(
        'format' => 1,
        'schools' => $schools,
        'datasets' => array(),
    );
    foreach ($summary as $item) {
        list($dataset, $school, $count, $hash) = $item;
        if (!isset($manifest['datasets'][$dataset])) {
            $manifest['datasets'][$dataset] = array();
        }
        $manifest['datasets'][$dataset][$school] = array(
            'rows' => $count,
            'sha256' => $hash,
        );
    }
    $manifestPhp = "<?php\n/** AUTO-GENERATED by tools/scoped-workload-sync.php. */\nreturn " . var_export($manifest, true) . ";\n";
    if (file_put_contents($manifestPath, $manifestPhp) === false) {
        fwrite(STDERR, "WRITE FAIL: " . $manifestPath . "\n");
        $ok = false;
    } else {
        @touch($manifestPath, time() + 1);
    }
}

if ($ok) {
    echo "\nScoped workload datasets are synchronized.\n";
    exit(0);
}

echo "\nScoped workload datasets are NOT synchronized. Run:\n"
    . "  php tools/scoped-workload-sync.php --write\n";
exit(1);
